# Generated by Django 4.2.11 on 2024-05-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('submissions', '0001_initial'), ('submissions', '0002_alter_language_name'), ('submissions', '0003_verdict'), ('submissions', '0004_submission'), ('submissions', '0005_submission_secondary_key_submission_statistic_and_more'), ('submissions', '0006_submission_index'), ('submissions', '0007_alter_submission_index')]

    dependencies = [
        ('ranking', '0126_virtualstart_addition'),
        ('clist', '0146_contest_merging_contests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('extensions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('penalty', models.BooleanField(default=True)),
                ('solved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('contest_time', models.DurationField()),
                ('problem_short', models.CharField(max_length=50)),
                ('run_time', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.account')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.contest')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.language')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.verdict')),
                ('secondary_key', models.CharField(default='', max_length=50)),
                ('statistic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ranking.statistics')),
                ('index', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('statistic', 'secondary_key', 'problem_short')},
            },
        ),
    ]
