# Generated by Django 4.2.11 on 2024-05-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0126_virtualstart_addition'),
        ('submissions', '0001_initial_squashed_0007_alter_submission_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='secondary_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.statistics'),
        ),
    ]
