# Generated by Django 4.2.11 on 2024-05-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_alter_submission_secondary_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='index',
        ),
    ]
