# Generated by Django 4.2.11 on 2024-05-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_remove_submission_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='failed_test',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('test_number', models.IntegerField()),
                ('run_time', models.FloatField(blank=True, default=None, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.verdict')),
            ],
            options={
                'unique_together': {('submission', 'test_number')},
            },
        ),
    ]
