# Generated by Django 4.2.11 on 2024-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_submission_failed_test_testing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testing',
            name='secondary_key',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='testing',
            unique_together={('submission', 'secondary_key')},
        ),
    ]
