# Generated by Django 4.2.11 on 2024-05-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_alter_testing_unique_together_testing_secondary_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contest_time',
            field=models.DurationField(db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='failed_test',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_short',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='run_time',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='run_time',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='test_number',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
