# Generated by Django 4.2.11 on 2024-05-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_alter_submission_contest_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='problem_short',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
    ]
