# Generated by Django 4.2.11 on 2024-05-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_testing_problem_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='submissions.language'),
        ),
    ]
