# Generated by Django 4.2.11 on 2024-05-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_testing_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='language',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='problem_short',
        ),
    ]
