# Generated by Django 4.2.11 on 2024-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_remove_testing_language_remove_testing_problem_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='contest_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testing',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
