# Generated by Django 4.2.11 on 2024-05-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0146_contest_merging_contests'),
        ('submissions', '0016_testing_contest_time_testing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clist.problem'),
        ),
    ]
