# Generated by Django 4.2.11 on 2024-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_alter_submission_current_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_attempt',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
