# Generated by Django 4.2.11 on 2024-05-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0126_virtualstart_addition'),
        ('clist', '0148_contest_has_submissions_tests'),
        ('submissions', '0021_submission_submissions_contest_bfe680_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem_key',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ranking.account'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='clist.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='clist.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ranking.statistics'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='submissions.submission'),
        ),
    ]
