# Generated by Django 4.2.11 on 2024-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_submission_problem_key_alter_submission_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem_key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
