# Generated by Django 2.2.10 on 2020-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0006_remove_token_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='data_header',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
