# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0009_service_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='token',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
