# Generated by Django 3.1.14 on 2022-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0011_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email_field',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='state_field',
            field=models.CharField(default='state', max_length=255),
        ),
    ]
