# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 02:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='coder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder'),
        ),
    ]
