# Generated by Django 2.1.7 on 2019-03-29 22:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='message',
            field=jsonfield.fields.JSONField(),
        ),
    ]
