# Generated by Django 2.2.13 on 2020-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0031_auto_20201008_2322'),
        ('tg', '0006_chat_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='coders',
            field=models.ManyToManyField(blank=True, related_name='chats', to='true_coders.Coder'),
        ),
    ]
