# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_command',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='history',
            name='message',
            field=models.JSONField(),
        ),
    ]
