# Generated by Django 3.1.12 on 2021-07-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_chat_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
