# Generated by Django 5.1.7 on 2025-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0013_chat_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='replying_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
