# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-02 23:48


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_coders', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('deadline_registration', models.DateTimeField()),
                ('coders', models.ManyToManyField(blank=True, to='true_coders.Coder')),
                ('teams', models.ManyToManyField(blank=True, to='true_coders.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
