# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 11:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
