# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 19:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegistration',
            new_name='Registration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teams',
        ),
    ]
