# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 23:23


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
    ]
