# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 23:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180204_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Registration'),
        ),
    ]
