# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 00:57


from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_enumfield.db.fields
import events.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0012_coder_phone_number'),
        ('events', '0014_auto_20180205_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('first_name_native', models.CharField(blank=True, max_length=255)),
                ('last_name_native', models.CharField(blank=True, max_length=255)),
                ('middle_name_native', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('tshirt_size', django_enumfield.db.fields.EnumField(blank=True, default=1, enum=events.models.TshirtSize, null=True)),
                ('coder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='coders',
        ),
        migrations.AddField(
            model_name='response',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='response',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='true_coders.Organization'),
        ),
    ]
