# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 01:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0013_auto_20180206_0132'),
        ('events', '0017_auto_20180206_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Participant'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Team'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('coder', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'event')]),
        ),
    ]
