# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 01:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20180206_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='coder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
