# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 03:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_participant_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_coach_set', to='events.Participant'),
        ),
    ]
