# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 22:03


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20180206_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_conf',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
