# Generated by Django 2.1.7 on 2019-09-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_participant__team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='participants',
        ),
        migrations.AlterField(
            model_name='participant',
            name='_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.Team'),
        ),
    ]
