# Generated by Django 2.1.7 on 2019-09-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20190908_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='_team',
            new_name='team',
        ),
    ]
