# Generated by Django 3.1.13 on 2021-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='looking_for',
            field=models.BooleanField(default=False),
        ),
    ]
