version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements/"
    schedule:
      interval: daily
    target-branch: master
    reviewers:
      - aropan
    assignees:
      - aropan
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
    reviewers:
      - aropan
    assignees:
      - aropan
    allow:
      - dependency-type: direct
