version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/legacy"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
