# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 00:37


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_coders', '__first__'),
        ('clist', '0006_auto_20170918_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('coder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('previous_days', models.IntegerField(default=14)),
                ('min_delay_after_end', models.DurationField()),
                ('max_delay_after_end', models.DurationField()),
                ('delay_on_error', models.DurationField()),
                ('delay_on_success', models.DurationField(blank=True, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clist.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.Contest')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(blank=True, default=None, max_length=17, null=True)),
                ('solving', models.IntegerField(blank=True, default=0)),
                ('upsolving', models.IntegerField(blank=True, default=0)),
                ('addition', jsonfield.fields.JSONField(blank=True, default={})),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Account')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.Contest')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together=set([('account', 'contest')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('coder', 'resource'), ('resource', 'key')]),
        ),
    ]
