# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 01:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0006_auto_20170918_0057'),
        ('ranking', '0002_auto_20170924_0038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('resource', 'key')]),
        ),
    ]
