# Generated by Django 2.1.7 on 2019-05-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20170924_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='previous_days',
        ),
    ]
