# Generated by Django 2.1.7 on 2019-06-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20190606_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.Contest'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Party'),
        ),
    ]
