# Generated by Django 2.1.7 on 2019-11-24 16:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0014_auto_20191123_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
