# Generated by Django 2.1.7 on 2020-01-06 23:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0015_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
