# Generated by Django 2.1.7 on 2020-01-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0016_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
