# Generated by Django 2.1.7 on 2020-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0021_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
