# Generated by Django 2.1.7 on 2020-01-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0024_resource_profile_url'),
        ('ranking', '0022_stage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='slug',
        ),
        migrations.AddField(
            model_name='stage',
            name='contest',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='clist.Contest'),
            preserve_default=False,
        ),
    ]
