# Generated by Django 2.2.10 on 2020-02-14 00:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0025_auto_20200119_1008'),
        ('ranking', '0023_auto_20200127_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('deadline', models.DateTimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
