# Generated by Django 2.2.10 on 2020-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0028_remove_autorating_time_to_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
