# Generated by Django 2.2.10 on 2020-04-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0029_statistics_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='solution',
        ),
    ]
