# Generated by Django 2.2.10 on 2020-04-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0030_remove_statistics_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='description',
        ),
    ]
