# Generated by Django 2.2.10 on 2020-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0035_auto_20200429_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='n_contests',
            field=models.IntegerField(default=0),
        ),
    ]
