# Generated by Django 2.2.10 on 2020-05-03 22:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0037_account_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='n_contests',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
