# Generated by Django 2.2.10 on 2020-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0038_auto_20200503_2219'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country'], name='ranking_acc_resourc_fe9bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'last_activity'], name='ranking_acc_resourc_c26e26_idx'),
        ),
    ]
