# Generated by Django 2.2.10 on 2020-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0040_auto_20200504_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
