# Generated by Django 2.2.10 on 2020-05-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0043_auto_20200511_1309'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_61bc33_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_6766dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_407632_idx',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country'], name='ranking_acc_resourc_fe9bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_contests', '-id'], name='ranking_acc_resourc_7441e5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'rating', '-id'], name='ranking_acc_resourc_e0e33b_idx'),
        ),
    ]
