# Generated by Django 2.2.10 on 2020-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0045_auto_20200511_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating50',
            field=models.SmallIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
