# Generated by Django 2.2.13 on 2020-09-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0051_account_n_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.Account'),
        ),
    ]
