# Generated by Django 2.2.13 on 2020-10-10 01:03

from django.db import migrations
import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0053_auto_20200929_2156'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['key'], name='ranking_acc_key_139169_gist'),
        ),
    ]
