# Generated by Django 2.2.13 on 2020-11-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0055_auto_20201009_0735'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['place_as_int', '-created'], name='ranking_sta_place_a_42252c_idx'),
        ),
    ]
