# Generated by Django 3.1.12 on 2021-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0060_auto_20210802_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='long_contest_delay',
            field=models.DurationField(default='02:00:00'),
        ),
        migrations.AddField(
            model_name='module',
            name='long_contest_idle',
            field=models.DurationField(default='06:00:00'),
        ),
    ]
