# Generated by Django 3.1.14 on 2022-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0066_account_global_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_writers'], name='ranking_acc_resourc_730d4f_idx'),
        ),
    ]
