# Generated by Django 3.1.14 on 2022-05-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0067_auto_20220514_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='has_accounts_infos_update',
        ),
        migrations.RemoveField(
            model_name='module',
            name='multi_account_allowed',
        ),
    ]
