# Generated by Django 3.1.14 on 2022-07-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0068_auto_20220522_1139'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'account'], name='ranking_sta_contest_14aefd_idx'),
        ),
    ]
