# Generated by Django 3.1.14 on 2022-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0069_auto_20220728_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='min_delay_after_end',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
