# Generated by Django 3.1.14 on 2022-11-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0070_auto_20221029_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_submission',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
