# Generated by Django 3.1.14 on 2022-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0071_account_last_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='skip_in_stats',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
