# Generated by Django 3.1.14 on 2022-12-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0072_statistics_skip_in_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='advanced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'advanced'], name='ranking_sta_contest_87998c_idx'),
        ),
    ]
