# Generated by Django 3.1.14 on 2022-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0073_auto_20221219_0018'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_87998c_idx',
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'account', 'advanced'], name='ranking_sta_contest_03a6e8_idx'),
        ),
    ]
