# Generated by Django 3.1.14 on 2022-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0075_auto_20221226_1643'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_03a6e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_87998c_idx',
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'advanced', 'place_as_int'], name='ranking_sta_contest_2fa9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'account', 'advanced', 'place_as_int'], name='ranking_sta_contest_0a8456_idx'),
        ),
    ]
