# Generated by Django 3.1.14 on 2022-12-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0076_auto_20221226_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='skip_in_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['account', 'skip_in_stats'], name='ranking_sta_account_783160_idx'),
        ),
    ]
