# Generated by Django 3.1.14 on 2023-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0078_auto_20230329_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
