# Generated by Django 3.1.14 on 2023-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0079_statistics_last_activity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'key'], name='ranking_acc_resourc_c474c4_idx'),
        ),
    ]
