# Generated by Django 4.2.3 on 2023-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0083_auto_20230722_1026'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['place_as_int'], name='ranking_sta_place_a_58facc_idx'),
        ),
    ]
