# Generated by Django 4.2.3 on 2023-08-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0085_place_as_int_and_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='need_verification',
            field=models.BooleanField(default=False),
        ),
    ]
