# Generated by Django 4.2.3 on 2023-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0086_account_need_verification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_f2088d_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_7441e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_e0e33b_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_ab54a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_fbe971_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_297811_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_49006c_idx',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'rating'], name='ranking_acc_resourc_f6b3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-rating'], name='ranking_acc_resourc_c76f81_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-rating50'], name='ranking_acc_resourc_356b87_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'last_activity'], name='ranking_acc_resourc_c26e26_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-last_activity'], name='ranking_acc_resourc_e9c631_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_contests'], name='ranking_acc_resourc_23c237_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-n_contests'], name='ranking_acc_resourc_1844d7_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-n_writers'], name='ranking_acc_resourc_48f383_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-updated'], name='ranking_acc_resourc_9563d5_idx'),
        ),
    ]
