# Generated by Django 4.2.3 on 2023-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0087_remove_account_ranking_acc_resourc_f2088d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_rank',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='resource_rank',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
