# Generated by Django 4.2.3 on 2023-09-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0088_account_country_rank_account_resource_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='resource_rank',
            new_name='rank',
        ),
    ]
