# Generated by Django 4.2.3 on 2023-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0093_statistics_rating_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='long_contest_divider',
            field=models.IntegerField(default=15),
        ),
    ]
