# Generated by Django 4.2.3 on 2023-10-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0094_alter_module_long_contest_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enable',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
    ]
