# Generated by Django 4.2.3 on 2023-10-14 21:36

from django.db import migrations, models

import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0126_alter_contest_has_fixed_rating_prediction_field'),
        ('ranking', '0096_accountrenaming'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountrenaming',
            unique_together={('resource', 'old_key')},
        ),
        migrations.AddIndex(
            model_name='accountrenaming',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['old_key'], name='ranking_acc_old_key_62d645_gist'),
        ),
        migrations.AddIndex(
            model_name='accountrenaming',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['new_key'], name='ranking_acc_new_key_2441d0_gist'),
        ),
        migrations.AddIndex(
            model_name='accountrenaming',
            index=models.Index(fields=['resource', 'old_key'], name='ranking_acc_resourc_1321b1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrenaming',
            index=models.Index(fields=['resource', 'new_key'], name='ranking_acc_resourc_23f049_idx'),
        ),
    ]
