# Generated by Django 4.2.3 on 2023-10-15 09:01

from django.db import migrations, models
import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0097_alter_accountrenaming_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-rating'], name='ranking_acc_resourc_8c3ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-rating50'], name='ranking_acc_resourc_da0a37_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-last_activity'], name='ranking_acc_resourc_f80307_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-n_contests'], name='ranking_acc_resourc_f5dc85_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-n_writers'], name='ranking_acc_resourc_bf96b0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-updated'], name='ranking_acc_resourc_a053f8_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', 'overall_rank'], name='ranking_acc_resourc_ff08ca_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-overall_rank'], name='ranking_acc_resourc_2c15ac_idx'),
        ),
    ]
