# Generated by Django 4.2.3 on 2023-10-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0098_account_ranking_acc_key_449bb8_gist_and_more'),
    ]

    operations = []
