# Generated by Django 4.2.3 on 2023-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0099_remove_account_ranking_acc_key_449bb8_gist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-rating'], name='ranking_acc_country_4516ee_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-rating50'], name='ranking_acc_country_f60f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-last_activity'], name='ranking_acc_country_79c57d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-n_contests'], name='ranking_acc_country_943961_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-n_writers'], name='ranking_acc_country_815bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-updated'], name='ranking_acc_country_684e45_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', 'overall_rank'], name='ranking_acc_country_028f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-overall_rank'], name='ranking_acc_country_c932f9_idx'),
        ),
    ]
