# Generated by Django 4.2.3 on 2023-11-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0101_account_ranking_acc_key_449bb8_gist'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_key_449bb8_gist',
        ),
    ]
