# Generated by Django 4.2.3 on 2023-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0103_account_ranking_acc_key_449bb8_gist'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_3e0b3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_6512c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_ff08ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_2c15ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_028f2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_c932f9_idx',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='overall_rank',
            new_name='resource_rank',
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'resource_rank'], name='ranking_acc_resourc_e5c899_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', '-resource_rank'], name='ranking_acc_resourc_d31669_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', 'resource_rank'], name='ranking_acc_resourc_e828ef_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'country', '-resource_rank'], name='ranking_acc_resourc_ad6e17_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', 'resource_rank'], name='ranking_acc_country_550b04_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['country', '-resource_rank'], name='ranking_acc_country_695ce4_idx'),
        ),
    ]
