# Generated by Django 4.2.3 on 2023-12-01 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0068_delete_virtualstart'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ranking', '0104_remove_account_ranking_acc_resourc_3e0b3f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_starts', to='true_coders.coder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['coder', 'content_type', 'object_id'], name='ranking_vir_coder_i_fa3096_idx')],
                'unique_together': {('coder', 'content_type', 'object_id')},
            },
        ),
    ]
