# Generated by Django 4.2.3 on 2023-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0105_virtualstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrenaming',
            name='new_key',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
