# Generated by Django 4.2.3 on 2023-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0107_alter_accountrenaming_new_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
