# Generated by Django 4.2.3 on 2023-12-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0108_account_is_subscribed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'name'], name='ranking_acc_resourc_19a0d1_idx'),
        ),
    ]
