# Generated by Django 4.2.3 on 2023-12-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0109_account_ranking_acc_resourc_19a0d1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
