# Generated by Django 4.2.7 on 2024-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0138_contest_trial_standings_url'),
        ('ranking', '0111_alter_account_deleted_alter_account_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='contests',
            field=models.ManyToManyField(blank=True, related_name='stages', to='clist.contest'),
        ),
    ]
