# Generated by Django 4.2.10 on 2024-03-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0112_stage_contests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='clist.contest'),
        ),
    ]
