# Generated by Django 4.2.11 on 2024-03-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0141_problem_skip_rating'),
        ('ranking', '0116_rename_new_contests_stage_contests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='contests',
            field=models.ManyToManyField(blank=True, related_name='stages', through='ranking.StageContest', to='clist.contest'),
        ),
    ]
