# Generated by Django 4.2.11 on 2024-03-31 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0117_alter_stage_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecontest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagecontest',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
