# Generated by Django 4.2.11 on 2024-04-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0141_problem_skip_rating'),
        ('ranking', '0119_countryaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countryaccount',
            unique_together={('resource', 'country')},
        ),
    ]
