# Generated by Django 4.2.11 on 2024-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0121_countryaccount_n_rating_accounts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_057da3_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_9b17d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_34b7c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_4fdb9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_0531f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_fe9631_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_96dbbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_977a09_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_e55400_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_f1ec91_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_81baef_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_18a92d_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_b6db42_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_504afb_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_7144e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_e33742_idx',
        ),
        migrations.RemoveField(
            model_name='countryaccount',
            name='rating50',
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', 'rating', 'country'], name='ranking_cou_resourc_c16c02_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', '-rating', 'country'], name='ranking_cou_resourc_ab2725_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', 'resource_rank', 'country'], name='ranking_cou_resourc_49d551_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', '-resource_rank', 'country'], name='ranking_cou_resourc_a989ae_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', 'n_accounts', 'country'], name='ranking_cou_resourc_63b9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=models.Index(fields=['resource', '-n_accounts', 'country'], name='ranking_cou_resourc_915a45_idx'),
        ),
    ]
