# Generated by Django 4.2.11 on 2024-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0123_account_last_rating_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryaccount',
            name='raw_rating',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
