# Generated by Django 4.2.11 on 2024-04-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0125_virtualstart_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualstart',
            name='addition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
