# Generated by Django 4.2.11 on 2024-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0126_virtualstart_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='try_fill_missed_ranks_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='try_renaming_check_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
