# Generated by Django 4.2.11 on 2024-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0127_account_try_fill_missed_ranks_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='shortly_after',
            field=models.DurationField(blank=True, default='00:30:00'),
        ),
    ]
