# Generated by Django 4.2.11 on 2024-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0128_module_shortly_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='delay_shortly_after',
            field=models.DurationField(blank=True, default='00:05:00'),
        ),
    ]
