# Generated by Django 5.1.3 on 2024-11-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0165_contest_variables'),
        ('ranking', '0133_subsriptions_and_parsestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsestatistics',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clist.contest'),
        ),
    ]
