# Generated by Django 5.1.3 on 2024-12-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0165_contest_variables'),
        ('ranking', '0134_alter_parsestatistics_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsestatistics',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_statistics', to='clist.contest'),
        ),
    ]
