# Generated by Django 5.1.4 on 2024-12-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ranking', '0136_statistics_penalty_and_more'), ('ranking', '0137_account_rating_update_time')]

    dependencies = [
        ('clist', '0166_contest_promotion'),
        ('ranking', '0135_alter_parsestatistics_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='penalty',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['place_as_int', '-solving', 'penalty'], name='ranking_sta_place_a_280c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'place_as_int', '-solving', 'penalty', 'id'], name='ranking_sta_contest_5962eb_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='rating_update_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
