# Generated by Django 5.1.4 on 2024-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0136_rating_update_time_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_place_a_c7984a_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_place_a_42252c_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_14aefd_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_account_226235_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_2fa9e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_0a8456_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_place_a_764576_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_place_a_280c4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistics',
            name='ranking_sta_contest_5962eb_idx',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='new_global_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
