# Generated by Django 5.1.4 on 2024-12-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0137_remove_statistics_ranking_sta_place_a_c7984a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='submissions_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
