# Generated by Django 5.1.5 on 2025-02-08 22:49

import django.db.models.deletion
from django.db import connection, migrations, models
from tqdm import tqdm

import pyclist.indexes
from utils.logger import suppress_db_logging_context


def fill_resource(apps, schema_editor):
    Statistics = apps.get_model('ranking', 'Statistics')
    Contest = apps.get_model('clist', 'Contest')

    statistics_table = Statistics._meta.db_table
    contest_table = Contest._meta.db_table

    total_records = Statistics.objects.filter(resource_id__isnull=True).count()
    batch_size = 1000
    num_batches = (total_records + batch_size - 1) // batch_size

    with connection.cursor() as cursor, suppress_db_logging_context():
        for batch_num in tqdm(range(num_batches), desc='Updating resources'):
            query = f'''
                WITH cte AS (
                    SELECT S.id
                    FROM {statistics_table} AS S
                    JOIN {contest_table} AS C ON S.contest_id = C.id
                    WHERE S.resource_id IS NULL
                    LIMIT {batch_size}
                )
                UPDATE {statistics_table} AS S
                SET resource_id = C.resource_id
                FROM {contest_table} AS C
                WHERE S.id IN (SELECT id FROM cte)
                AND S.contest_id = C.id;
            '''
            cursor.execute(query)


class Migration(migrations.Migration):

    replaces = [('ranking', '0139_account_n_listvalues'), ('ranking', '0140_statistics_n_first_ac_statistics_solved_and_more'), ('ranking', '0141_rename_solved_statistics_n_solved_and_more'), ('ranking', '0142_account_n_first_ac_account_n_solved_and_more'), ('ranking', '0143_account_n_total_solved_account_total_solving_and_more'), ('ranking', '0144_alter_statistics_n_upsolved_and_more'), ('ranking', '0145_alter_account_n_upsolved_alter_account_upsolving'), ('ranking', '0146_statistics_resource'), ('ranking', '0148_remove_account_ranking_acc_resourc_f6b3a9_idx_and_more'), ('ranking', '0148_remove_account_ranking_acc_resourc_a84e72_idx_and_more'), ('ranking', '0147_alter_statistics_resource'), ('ranking', '0148_account_ranking_acc_resourc_700c49_idx_and_more'), ('ranking', '0149_statistics_statistics_created_top3')]

    dependencies = [
        ('clist', '0170_contest_upsolving_key_contest_upsolving_url'),
        ('clist', '0172_resource_has_statistic_n_first_ac_and_more'),
        ('clist', '0176_rename_has_statistic_upsolving_contest_has_unlimited_statistics'),
        ('ranking', '0138_account_submissions_info'),
        ('true_coders', '0075_coderlist_account_update_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='n_listvalues',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='n_first_ac',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='n_solved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='n_first_ac',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='n_solved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='solving',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='n_total_solved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='total_solving',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='n_total_solved',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_solving',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='n_upsolved',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='upsolving',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='n_upsolved',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='upsolving',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.resource'),
        ),
        migrations.RunPython(fill_resource),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_f6b3a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_c76f81_idx',
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'rating'], name='ranking_acc_resourc_f6b3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-rating'], name='ranking_acc_resourc_c76f81_idx'),
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_a84e72_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_730d4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_d3d8b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_356b87_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_c26e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_e9c631_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_23c237_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_1844d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_48f383_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_9563d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_8c3ca5_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_da0a37_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_f80307_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_f5dc85_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_bf96b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_a053f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_4516ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_f60f9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_79c57d_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_943961_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_815bbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_684e45_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_e5c899_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_d31669_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_e828ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_ad6e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_550b04_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_country_695ce4_idx',
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'rating50'], name='ranking_acc_resourc_a84e72_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-rating50'], name='ranking_acc_resourc_356b87_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'last_activity'], name='ranking_acc_resourc_c26e26_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-last_activity'], name='ranking_acc_resourc_e9c631_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'n_contests'], name='ranking_acc_resourc_23c237_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_contests'], name='ranking_acc_resourc_1844d7_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'n_writers'], name='ranking_acc_resourc_730d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_writers'], name='ranking_acc_resourc_48f383_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'updated'], name='ranking_acc_resourc_d3d8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-updated'], name='ranking_acc_resourc_9563d5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'resource_rank'], name='ranking_acc_resourc_e5c899_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-resource_rank'], name='ranking_acc_resourc_d31669_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'total_solving'], name='ranking_acc_resourc_fbaf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-total_solving'], name='ranking_acc_resourc_a32892_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'n_total_solved'], name='ranking_acc_resourc_30f792_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_total_solved'], name='ranking_acc_resourc_1c79de_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'n_first_ac'], name='ranking_acc_resourc_2226e6_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_first_ac'], name='ranking_acc_resourc_ff4b92_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-rating'], name='ranking_acc_resourc_8c3ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-rating50'], name='ranking_acc_resourc_da0a37_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-last_activity'], name='ranking_acc_resourc_f80307_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-n_contests'], name='ranking_acc_resourc_f5dc85_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-n_writers'], name='ranking_acc_resourc_bf96b0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-updated'], name='ranking_acc_resourc_a053f8_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', 'resource_rank'], name='ranking_acc_resourc_e828ef_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-resource_rank'], name='ranking_acc_resourc_ad6e17_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-total_solving'], name='ranking_acc_resourc_e5d59b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-n_total_solved'], name='ranking_acc_resourc_431ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-n_first_ac'], name='ranking_acc_resourc_3b7160_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-rating'], name='ranking_acc_country_4516ee_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-rating50'], name='ranking_acc_country_f60f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-last_activity'], name='ranking_acc_country_79c57d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-n_contests'], name='ranking_acc_country_943961_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-n_writers'], name='ranking_acc_country_815bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-updated'], name='ranking_acc_country_684e45_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', 'resource_rank'], name='ranking_acc_country_550b04_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-resource_rank'], name='ranking_acc_country_695ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-total_solving'], name='ranking_acc_country_887721_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-n_total_solved'], name='ranking_acc_country_ce4c30_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-n_first_ac'], name='ranking_acc_country_07db81_idx'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.resource'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'last_rating_activity'], name='ranking_acc_resourc_700c49_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-last_rating_activity'], name='ranking_acc_resourc_b6a69b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'last_submission'], name='ranking_acc_resourc_d2c9be_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-last_submission'], name='ranking_acc_resourc_33e161_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-last_rating_activity'], name='ranking_acc_resourc_fed542_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', '-last_submission'], name='ranking_acc_resourc_0c30cc_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-last_rating_activity'], name='ranking_acc_country_0ac29d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['country', '-last_submission'], name='ranking_acc_country_5564db_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(condition=models.Q(('place_as_int__lte', 3)), fields=['-created'], name='statistics_created_top3'),
        ),
    ]
