# Generated by Django 5.1.5 on 2025-02-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0140_account_n_bronze_account_n_gold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='n_medal_contests',
        ),
    ]
