# Generated by Django 5.1.5 on 2025-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0141_remove_account_n_medal_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='medal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
