# Generated by Django 5.1.5 on 2025-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0142_statistics_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='medal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
