# Generated by Django 5.1.5 on 2025-02-15 00:07

import django.db.models.functions.text
from django.db import migrations, models

import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0171_resource_has_statistic_medal'),
        ('ranking', '0143_alter_statistics_medal'),
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.ExpressionIndex(models.F('resource'), django.db.models.functions.text.Upper('key'), expressions=[models.F('resource'), django.db.models.functions.text.Upper('key')], name='ranking_account_f7968a_idx'),
        ),
    ]
