# Generated by Django 5.1.5 on 2025-02-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ranking', '0145_finalist'), ('ranking', '0146_finalist_accounts'), ('ranking', '0147_finalist_unique_finalist_name'), ('ranking', '0148_remove_finalist_coders_finalistresourceinfo'), ('ranking', '0149_finalistresourceinfo_updated'), ('ranking', '0150_finalistresourceinfo_n_ratings'), ('ranking', '0151_remove_finalistresourceinfo_n_ratings_and_more'), ('ranking', '0152_finalist_achievement_statistics_and_more'), ('ranking', '0153_finalist_achievement_hash')]

    dependencies = [
        ('clist', '0172_resource_has_account_n_writers'),
        ('clist', '0173_contest_finalists_info'),
        ('ranking', '0144_account_ranking_account_f7968a_idx'),
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.contest')),
                ('accounts', models.ManyToManyField(blank=True, to='ranking.account')),
                ('achievement_statistics', models.ManyToManyField(blank=True, to='ranking.statistics')),
                ('achievement_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('achievement_hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('contest', 'name'), name='unique_finalist_name')],
            },
        ),
        migrations.CreateModel(
            name='FinalistResourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('finalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.finalist')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.resource')),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('ratings', models.JSONField(blank=True, default=list)),
            ],
            options={
                'unique_together': {('finalist', 'resource')},
            },
        ),
    ]
