# Generated by Django 5.1.5 on 2025-03-23 22:29

import pyclist.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ranking', '0146_account_n_first_places_account_n_second_places_and_more'), ('ranking', '0147_account_n_top_ten_places_account_n_total_places'), ('ranking', '0148_rename_n_total_places_account_n_places'), ('ranking', '0149_remove_countryaccount_ranking_cou_resourc_680ff7_idx_and_more')]

    dependencies = [
        ('clist', '0174_resource_has_statistic_place'),
        ('ranking', '0145_add_finalist'),
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='n_first_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='n_second_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='n_third_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='n_top_ten_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='n_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_680ff7_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_c16c02_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_ab2725_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_49d551_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_a989ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_63b9ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_915a45_idx',
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_bronze',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_gold',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_medals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_other_medals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_silver',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals'], name='ranking_acc_resourc_56527d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_first_places', '-n_second_places', '-n_third_places', '-n_top_ten_places'], name='ranking_acc_resourc_d4079d_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country'], name='ranking_cou_resourc_680ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'rating', 'country'], name='ranking_cou_resourc_c16c02_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-rating', 'country'], name='ranking_cou_resourc_ab2725_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'resource_rank', 'country'], name='ranking_cou_resourc_49d551_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-resource_rank', 'country'], name='ranking_cou_resourc_a989ae_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'n_accounts', 'country'], name='ranking_cou_resourc_63b9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_accounts', 'country'], name='ranking_cou_resourc_915a45_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals', 'country'], name='ranking_cou_resourc_f82532_idx'),
        ),
    ]
