# Generated by Django 5.1.8 on 2025-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0174_more_fields'),
        ('ranking', '0146_more_fields'),
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource'], name='ranking_acc_resourc_6d3981_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(condition=models.Q(('updated__isnull', False)), fields=['resource', 'updated'], name='account_updated'),
        ),
    ]
