# Generated by Django 5.1.8 on 2025-11-09 06:32

import django.db.models.deletion
import pyclist.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ranking', '0148_account_account_type_and_more'), ('ranking', '0149_alter_account_account_type'), ('ranking', '0150_account_ranking_acc_resourc_b4b309_idx'), ('ranking', '0151_account_ranking_acc_resourc_507c42_idx'), ('ranking', '0152_countryaccount_n_first_places_and_more'), ('ranking', '0153_account_related'), ('ranking', '0154_statistics_related'), ('ranking', '0155_remove_account_ranking_acc_resourc_56527d_idx_and_more')]

    dependencies = [
        ('clist', '0175_resource_allow_delete_archived_statistics'),
        ('clist', '0177_resource_n_team_accounts'),
        ('clist', '0180_resource_default_account_type'),
        ('ranking', '0147_account_ranking_acc_resourc_6d3981_idx_and_more'),
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'University')], default=1),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', 'n_contests'], name='ranking_acc_resourc_dcdfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', '-n_contests'], name='ranking_acc_resourc_1e8934_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', 'last_activity'], name='ranking_acc_resourc_521a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', '-last_activity'], name='ranking_acc_resourc_3c331a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals'], name='ranking_acc_resourc_79e886_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', '-n_first_places', '-n_second_places', '-n_third_places', '-n_top_ten_places'], name='ranking_acc_resourc_b85965_idx'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'University'), (3, 'Team')], default=1),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type'], name='ranking_acc_resourc_b4b309_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'country', 'account_type'], name='ranking_acc_resourc_507c42_idx'),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_first_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_second_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_third_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_top_ten_places',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_first_places', '-n_second_places', '-n_third_places', '-n_top_ten_places', 'country'], name='ranking_cou_resourc_773c4d_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_accounts', to='ranking.account'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.statistics'),
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_56527d_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ranking_acc_resourc_79e886_idx',
        ),
        migrations.RemoveIndex(
            model_name='countryaccount',
            name='ranking_cou_resourc_f82532_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='n_win',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='countryaccount',
            name='n_win',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_win', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals'], name='ranking_acc_resourc_4480c5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', 'account_type', '-n_win', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals'], name='ranking_acc_resourc_610eea_idx'),
        ),
        migrations.AddIndex(
            model_name='countryaccount',
            index=pyclist.indexes.DescNullsLastIndex(fields=['resource', '-n_win', '-n_gold', '-n_silver', '-n_bronze', '-n_other_medals', 'country'], name='ranking_cou_resourc_690d60_idx'),
        ),
    ]
