# Generated by Django 5.1.8 on 2025-11-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0148_account_account_type_and_more_squashed_0155_remove_account_ranking_acc_resourc_56527d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_statistics', to='ranking.statistics'),
        ),
    ]
