# Generated by Django 5.1.15 on 2026-02-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0186_problem_submissions_rate'),
        ('ranking', '0156_alter_statistics_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('log_type', models.CharField(choices=[('SUBMISSION', 'Submission')], max_length=16)),
                ('time', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.account')),
                ('contest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.contest')),
                ('resource', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.resource')),
                ('statistic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.statistics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
