# Generated by Django 5.1.15 on 2026-02-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0187_resource_has_submissions_statistics_log'),
        ('ranking', '0157_statisticslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticslog',
            name='log_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='statisticslog',
            constraint=models.UniqueConstraint(condition=models.Q(('log_id__isnull', False)), fields=('resource', 'contest', 'statistic', 'account', 'log_type', 'log_id'), name='unique_log_id'),
        ),
    ]
