# Generated by Django 5.1.15 on 2026-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0187_resource_has_submissions_statistics_log'),
        ('ranking', '0158_statisticslog_log_id_statisticslog_unique_log_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-time', 'resource', 'log_type', 'id'], name='ranking_sta_time_cb1294_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-time', 'resource', 'log_type', 'account', 'id'], name='ranking_sta_time_1b041b_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-time', 'resource', 'log_type', 'contest', 'id'], name='ranking_sta_time_7fac1e_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-modified', 'resource', 'log_type', 'id'], name='ranking_sta_modifie_2a6421_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-modified', 'resource', 'log_type', 'account', 'id'], name='ranking_sta_modifie_e97fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-modified', 'resource', 'log_type', 'contest', 'id'], name='ranking_sta_modifie_e2fa66_idx'),
        ),
    ]
