# Generated by Django 5.1.15 on 2026-02-21 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0188_alter_contest_options_alter_resource_options'),
        ('ranking', '0159_statisticslog_ranking_sta_time_cb1294_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statisticslog',
            name='ranking_sta_modifie_2a6421_idx',
        ),
        migrations.RemoveIndex(
            model_name='statisticslog',
            name='ranking_sta_modifie_e97fb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='statisticslog',
            name='ranking_sta_modifie_e2fa66_idx',
        ),
        migrations.AddField(
            model_name='statisticslog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 23, 2, 46, 854627, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-updated', '-time', 'resource', 'log_type', 'id'], name='ranking_sta_updated_e57d31_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-updated', '-time', 'resource', 'log_type', 'account', 'id'], name='ranking_sta_updated_c8f2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticslog',
            index=models.Index(fields=['-updated', '-time', 'resource', 'log_type', 'contest', 'id'], name='ranking_sta_updated_de62a5_idx'),
        ),
    ]
