# Generated by Django 5.1.15 on 2026-03-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0160_remove_statisticslog_ranking_sta_modifie_2a6421_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticslog',
            name='log_type',
            field=models.CharField(choices=[('SUBMISSION', 'Submission'), ('GAME', 'Game')], max_length=16),
        ),
    ]
