# Generated by Django 6.1 on 2026-08-14 22:10
# ruff: file-ignore[mutable-class-default]

from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("clist", "0191_rename_clist_probl_name_e9002d_gist_clist_problem_name_gist_and_more"),
        ("ranking", "0161_alter_statisticslog_log_type"),
        ("true_coders", "0074_coder_bookmarks"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=pyclist.indexes.DescNullsLastIndex(
                fields=["country", "-created"], name="ranking_acc_country_572c50_idx"
            ),
        ),
    ]
