# Generated by Django 6.1 on 2026-08-14 22:10
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ranking", "0162_account_ranking_acc_country_572c50_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="account",
            index=pyclist.indexes.DescNullsLastIndex(
                fields=["resource", "-created"], name="ranking_acc_resourc_894d35_idx"
            ),
        ),
    ]
