# Generated by Django 6.1 on 2026-08-14 22:10
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ranking", "0163_account_ranking_acc_resourc_894d35_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="account",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["key"], name="ranking_acc_key_c1df2b_gin"),
        ),
        AddIndexConcurrently(
            model_name="account",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["name"], name="ranking_acc_name_9ebdef_gin"),
        ),
        AddIndexConcurrently(
            model_name="accountrenaming",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["old_key"], name="ranking_acc_old_key_e13c80_gin"),
        ),
        AddIndexConcurrently(
            model_name="accountrenaming",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["new_key"], name="ranking_acc_new_key_eb2349_gin"),
        ),
    ]
