# Generated by Django 6.1 on 2026-08-14 22:12
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ranking", "0164_account_ranking_acc_key_c1df2b_gin_and_more"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="account",
            name="ranking_acc_key_139169_gist",
        ),
        RemoveIndexConcurrently(
            model_name="account",
            name="ranking_acc_name_26e7cf_gist",
        ),
        RemoveIndexConcurrently(
            model_name="accountrenaming",
            name="ranking_acc_old_key_62d645_gist",
        ),
        RemoveIndexConcurrently(
            model_name="accountrenaming",
            name="ranking_acc_new_key_2441d0_gist",
        ),
    ]
