# Generated by Django 6.1 on 2026-08-14 22:49
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clist", "0193_remove_contest_clist_conte_title_a56b78_gist_and_more"),
        ("ranking", "0165_remove_account_ranking_acc_key_139169_gist_and_more"),
        ("true_coders", "0076_remove_coder_true_coders_usernam_c4656d_gist"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="account",
            index=models.Index(
                fields=["resource", "-created"],
                name="ranking_acc_res_created_tmp",
            ),
        ),
        AddIndexConcurrently(
            model_name="account",
            index=models.Index(
                fields=["country", "-created"],
                name="ranking_acc_ctry_created_tmp",
            ),
        ),
        RemoveIndexConcurrently(
            model_name="account",
            name="ranking_acc_country_572c50_idx",
        ),
        RemoveIndexConcurrently(
            model_name="account",
            name="ranking_acc_resourc_894d35_idx",
        ),
        migrations.RenameIndex(
            model_name="account",
            new_name="ranking_acc_resourc_894d35_idx",
            old_name="ranking_acc_res_created_tmp",
        ),
        migrations.RenameIndex(
            model_name="account",
            new_name="ranking_acc_country_572c50_idx",
            old_name="ranking_acc_ctry_created_tmp",
        ),
    ]
