# Generated by Django 6.1 on 2026-08-14 22:58
# ruff: file-ignore[mutable-class-default]

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ranking", "0166_remove_account_ranking_acc_country_572c50_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE STATISTICS ranking_statistics_no_update_n_contests_stats
                ON ((addition -> '_no_update_n_contests'))
                FROM ranking_statistics
            """,
            reverse_sql="DROP STATISTICS ranking_statistics_no_update_n_contests_stats",
        ),
        migrations.RunSQL(
            sql="ANALYZE ranking_statistics",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
