# Generated by Django 6.1 on 2026-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0167_statistics_no_update_planner_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'University'), (3, 'Team'), (4, 'Member')], default=1),
        ),
    ]
