# Generated by Django 4.2.3 on 2023-08-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_coders', '0059_filter_enabled'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['coder', 'content_type', 'object_id'], name='notes_note_coder_i_378803_idx'), models.Index(fields=['content_type', 'object_id'], name='notes_note_content_7500a1_idx')],
                'unique_together': {('coder', 'content_type', 'object_id')},
            },
        ),
    ]
