#!/usr/bin/env python3

from pathlib import Path
from sysconfig import get_path

WEBPUSH_USER_AGENT_MIGRATION = """# Generated by Django 6.1 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpush", "0005_auto_20230614_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioninfo",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
"""


def replace_once(path: Path, old: str, new: str) -> None:
    content = path.read_text(encoding="utf-8")
    occurrences = content.count(old)
    if occurrences != 1:
        raise RuntimeError(f"expected exactly one occurrence in {path}, found {occurrences}")
    path.write_text(content.replace(old, new), encoding="utf-8")


def write_exact(path: Path, content: str) -> None:
    if path.exists():
        if path.read_text(encoding="utf-8") != content:
            raise RuntimeError(f"unexpected existing content in {path}")
        return
    path.write_text(content, encoding="utf-8")


def main() -> None:
    site_packages = Path(get_path("purelib"))
    replace_once(
        site_packages / "tastypie_swagger" / "mapping.py",
        "plural = not detail and method is 'get'",
        "plural = not detail and method == 'get'",
    )
    write_exact(
        site_packages / "webpush" / "migrations" / "0006_alter_subscriptioninfo_user_agent.py",
        WEBPUSH_USER_AGENT_MIGRATION,
    )


if __name__ == "__main__":
    main()
