# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 21:59


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180520_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.Notification'),
        ),
    ]
