# Generated by Django 2.2.13 on 2020-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20200613_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.CharField(choices=[('event', 'Event'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=16),
        ),
    ]
