# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='addition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
