# Generated by Django 3.1.13 on 2021-10-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='with_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='with_updates',
            field=models.BooleanField(default=True),
        ),
    ]
