# Generated by Django 3.1.14 on 2022-01-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20220110_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmessage',
            old_name='message',
            new_name='text',
        ),
    ]
