# Generated by Django 3.1.14 on 2022-01-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_auto_20220110_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
