# Generated by Django 3.1.14 on 2022-01-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0048_auto_20220111_2315'),
        ('notification', '0025_auto_20220111_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to='true_coders.coder'),
        ),
    ]
