# Generated by Django 3.1.14 on 2022-05-22 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_calendar_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='descriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Url'), (2, 'Host'), (3, 'Duration')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
