# Generated by Django 3.1.14 on 2022-07-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0032_auto_20220731_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notification',
        ),
    ]
