# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 01:01


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default=b'UTC', max_length=32)),
                ('settings', jsonfield.fields.JSONField(blank=True, default={})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('duration_from', models.IntegerField(blank=True, null=True)),
                ('duration_to', models.IntegerField(blank=True, null=True)),
                ('regex', models.CharField(blank=True, max_length=1000, null=True)),
                ('inverse_regex', models.BooleanField(default=False)),
                ('resources', jsonfield.fields.JSONField(blank=True, default=[])),
                ('categories', jsonfield.fields.JSONField(blank=True, default=['list', 'calendar', 'email', 'telegram', 'api'])),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_author_set', to='true_coders.Coder')),
                ('coders', models.ManyToManyField(blank=True, to='true_coders.Coder')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
