# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 15:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0005_auto_20180203_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='true_coders.Organization'),
        ),
    ]
