# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 21:04


from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0009_organization_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
