# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 22:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0010_coder_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='middle_name_native',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
