# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 01:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180206_0132'),
        ('true_coders', '0012_coder_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='author',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coders',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
