# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 03:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0013_auto_20180206_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='to_show',
            field=models.BooleanField(default=False),
        ),
    ]
