# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 11:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0014_filter_to_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
