# Generated by Django 2.2.10 on 2020-02-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0025_auto_20200119_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='party_admin_set', to='true_coders.Coder'),
        ),
    ]
