# Generated by Django 2.2.10 on 2020-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0026_party_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
