# Generated by Django 2.2.13 on 2020-10-10 01:22

from django.db import migrations
import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0030_coder_n_accounts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coder',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['username'], name='true_coders_usernam_c4656d_gist'),
        ),
    ]
