# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0031_auto_20201008_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='addition_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='coder',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='filter',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
