# Generated by Django 3.1.12 on 2021-07-03 00:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0037_auto_20210702_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list_set', to='true_coders.coder'),
        ),
    ]
