# Generated by Django 3.1.12 on 2021-07-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0040_auto_20210703_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listvalue',
            name='coder_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_values', to='true_coders.list'),
        ),
    ]
