# Generated by Django 3.1.12 on 2021-07-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0042_auto_20210703_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='CoderList',
        ),
    ]
