# Generated by Django 3.1.13 on 2021-10-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0045_coder_tshirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.party'),
        ),
    ]
