# Generated by Django 3.1.14 on 2022-03-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0049_coder_global_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='global_rating',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
