# Generated by Django 3.1.14 on 2022-08-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0050_auto_20220320_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
