# Generated by Django 4.2.3 on 2024-02-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0005_alter_eventlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgStatTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('table_name', models.CharField(max_length=255)),
                ('table_len', models.BigIntegerField()),
                ('tuple_count', models.BigIntegerField()),
                ('tuple_len', models.BigIntegerField()),
                ('tuple_percent', models.FloatField()),
                ('dead_tuple_count', models.BigIntegerField()),
                ('dead_tuple_len', models.BigIntegerField()),
                ('dead_tuple_percent', models.FloatField()),
                ('free_space', models.BigIntegerField()),
                ('free_percent', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('initiated', 'Initiated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('skipped', 'Skipped'), ('reverted', 'Reverted'), ('exception', 'Exception'), ('interrupted', 'Interrupted')], db_index=True, default='default', max_length=20),
        ),
    ]
