# Generated by Django 4.2.3 on 2024-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0006_pgstattuple_alter_eventlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstattuple',
            name='app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pgstattuple',
            name='table_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
