# Generated by Django 4.2.10 on 2024-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0007_pgstattuple_app_name_alter_pgstattuple_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='elapsed',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
