# Generated by Django 5.0.7 on 2024-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0008_eventlog_elapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='environment',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
