# Generated by Django 5.1 on 2024-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('logify', '0010_rename_pgstattuple_pgstat'), ('logify', '0011_pgstat_last_analyze_pgstat_last_autoanalyze_and_more'), ('logify', '0012_pgstat_table_size'), ('logify', '0013_pgstat_pretty_table_size'), ('logify', '0014_pgstat_diff_size_pgstat_pretty_diff_size'), ('logify', '0015_pgstat_initial_table_size')]

    dependencies = [
        ('logify', '0009_eventlog_environment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PgStatTuple',
            new_name='PgStat',
        ),
        migrations.AddField(
            model_name='pgstat',
            name='last_analyze',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='last_autoanalyze',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='last_autovacuum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='last_vacuum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='table_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='pretty_table_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='diff_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='pretty_diff_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstat',
            name='initial_table_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
