# Generated by Django 5.1.3 on 2024-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0010_pretty_pgstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='elapsed',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('exception', 'Exception'), ('interrupted', 'Interrupted'), ('warning', 'Warning')], db_index=True, default='none', max_length=20),
        ),
    ]
