# Generated by Django 5.1.3 on 2024-12-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0011_eventlog_error_alter_eventlog_elapsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='environment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
