# Generated by Django 5.1.3 on 2024-12-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0012_alter_eventlog_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('interrupted', 'Interrupted'), ('warning', 'Warning')], db_index=True, default='none', max_length=20),
        ),
    ]
