# Generated by Django 5.1.15 on 2026-08-01 11:20

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logify", "0013_alter_eventlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="job_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        AddIndexConcurrently(
            model_name="eventlog",
            index=models.Index(
                condition=models.Q(("status", "in_progress")),
                fields=["job_id", "environment"],
                name="event_job_inprogress_idx",
            ),
        ),
    ]
