# Generated by Django 5.1.15 on 2026-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logify', '0014_eventlog_job_id_eventlog_event_job_inprogress_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'permissions': (('view_all_live_updates', 'Can view all live updates'),)},
        ),
        migrations.AddField(
            model_name='eventlog',
            name='is_live_stream',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
