# Generated by Django 5.1.15 on 2026-08-01 17:32

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("logify", "0015_alter_eventlog_options_eventlog_is_live_stream"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="eventlog",
            index=models.Index(
                condition=models.Q(job_id__isnull=False),
                fields=["job_id", "environment"],
                name="event_job_environment_idx",
            ),
        ),
        RemoveIndexConcurrently(
            model_name="eventlog",
            name="event_job_inprogress_idx",
        ),
    ]
