# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 01:01


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_coders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('code_uri', models.TextField()),
                ('token_uri', models.TextField()),
                ('token_post', models.TextField(blank=True)),
                ('state_field', models.CharField(max_length=255)),
                ('user_id_field', models.CharField(max_length=255)),
                ('data_uri', models.TextField()),
                ('fa_icon', models.CharField(max_length=255)),
                ('url_profile', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data', jsonfield.fields.JSONField(null=True)),
                ('coder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_oauth.Service')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('service', 'user_id')]),
        ),
    ]
