# Generated by Django 2.1.7 on 2019-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='n_viewed_tokens',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='tokens_view_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
