# Generated by Django 2.1.7 on 2020-01-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0005_remove_service_url_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='data',
        ),
    ]
