# Generated by Django 5.1 on 2024-11-17 15:34

import utils.strings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('my_oauth', '0014_form_register_headers_form_register_url'), ('my_oauth', '0015_remove_form_slug'), ('my_oauth', '0016_alter_form_secret'), ('my_oauth', '0017_token_expires_at'), ('my_oauth', '0018_service_refresh_token_post_service_refresh_token_uri'), ('my_oauth', '0019_form_end_time_form_start_time')]

    dependencies = [
        ('my_oauth', '0013_alter_token_email_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='register_headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='register_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='form',
            name='slug',
        ),
        migrations.AlterField(
            model_name='form',
            name='secret',
            field=models.CharField(blank=True, default=utils.strings.generate_secret_64, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='refresh_token_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='refresh_token_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
