# Generated by Django 5.1.8 on 2025-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0015_form_service_code_args_service_code_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
