# Generated by Django 5.1.8 on 2025-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0016_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
