# Generated by Django 5.1.8 on 2025-09-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0017_form_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='grant_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Unassigned'), (2, 'Assigned'), (3, 'Approved')], db_index=True, default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_oauth.form')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_oauth.token')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('form', 'login'), name='unique_form_login'), models.UniqueConstraint(condition=models.Q(('token__isnull', False)), fields=('form', 'token'), name='unique_form_token_not_null')],
            },
        ),
    ]
