# Generated by Django 5.1.8 on 2025-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0018_form_grant_credentials_alter_form_title_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='approved_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
