# Generated by Django 5.1.8 on 2025-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('my_oauth', '0020_service_signed_field_service_signed_method'), ('my_oauth', '0021_alter_service_email_field'), ('my_oauth', '0022_service_signed_args_alter_service_data_uri'), ('my_oauth', '0023_alter_service_signed_args')]

    dependencies = [
        ('my_oauth', '0019_form_approved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='signed_field',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='signed_method',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='email_field',
            field=models.CharField(blank=True, default='email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_uri',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='signed_args',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
