# Generated by Django 5.1.15 on 2026-01-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0020_service_signed_field_service_signed_method_squashed_0023_alter_service_signed_args'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'permissions': (('view_form_stats', 'Can view form statistics'),)},
        ),
    ]
