# Generated by Django 5.1.15 on 2026-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_oauth', '0024_alter_credential_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'permissions': (('view_form_stats', 'Can view form statistics'),)},
        ),
    ]
