# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 01:01


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('true_coders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[(b'', b'...'), (b'email', b'Email'), (b'telegram', b'Telegram')], max_length=12)),
                ('before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.CharField(choices=[(b'', b'...'), (b'event', b'Event'), (b'hour', b'Hour'), (b'day', b'Day'), (b'week', b'Week'), (b'month', b'Month')], max_length=12)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[(b'', b'...'), (b'email', b'Email'), (b'telegram', b'Telegram')], max_length=12)),
                ('subject', models.CharField(max_length=4096)),
                ('message', models.TextField()),
                ('addition', jsonfield.fields.JSONField(blank=True, default={})),
                ('is_sent', models.BooleanField(default=False)),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
