# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 21:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='method',
        ),
        migrations.AddField(
            model_name='task',
            name='notification',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='notification.Notification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='method',
            field=models.CharField(max_length=12),
        ),
    ]
