# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 22:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180520_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='method',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.CharField(choices=[(b'', b'...'), (b'event', b'Event'), (b'hour', b'Hour'), (b'day', b'Day'), (b'week', b'Week'), (b'month', b'Month')], max_length=16),
        ),
    ]
