# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 22:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180520_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='whom',
        ),
    ]
