# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 23:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_task_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
