# Generated by Django 2.2.13 on 2020-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20190818_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
