# Generated by Django 2.2.13 on 2020-06-12 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20200606_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='before',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
