# Generated by Django 3.1.13 on 2021-10-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_auto_20211030_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='with_results',
            field=models.BooleanField(default=False),
        ),
    ]
