# Generated by Django 3.1.13 on 2021-11-22 21:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
