# Generated by Django 3.1.14 on 2022-07-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0028_auto_20220522_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='with_virtual',
            field=models.BooleanField(default=True),
        ),
    ]
