# Generated by Django 3.1.14 on 2022-07-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0031_auto_20220731_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notification_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
