# Generated by Django 3.1.14 on 2022-07-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0086_contest_registration_url'),
        ('notification', '0034_auto_20220731_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clist.contest'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['contest', 'account'], name='notificatio_contest_559967_idx'),
        ),
    ]
