# Generated by Django 3.1.14 on 2022-10-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0037_task_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
