# Generated by Django 4.2.3 on 2023-12-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0138_contest_trial_standings_url'),
        ('tg', '0012_chat_thread_id_alter_chat_chat_id_and_more'),
        ('ranking', '0107_alter_accountrenaming_new_key'),
        ('true_coders', '0068_delete_virtualstart'),
        ('notification', '0039_notification_clear_on_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coder_chat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tg.chat'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coder_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.coderlist'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.resource'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.account'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='contest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.contest'),
        ),
    ]
