# Generated by Django 5.1 on 2024-11-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('notification', '0042_remove_subscription_notificatio_contest_559967_idx_and_more'), ('notification', '0043_alter_subscription_accounts'), ('notification', '0044_alter_notification_coder_alter_subscription_coder'), ('notification', '0045_alter_notification_coder_alter_subscription_coder'), ('notification', '0046_subscription_coders_alter_subscription_accounts'), ('notification', '0047_subscription_notificatio_enable_2370eb_idx'), ('notification', '0048_subscription_last_contest_subscription_last_update'), ('notification', '0049_subscription_top_n_subscription_with_first_accepted'), ('notification', '0050_subscription_notificatio_resourc_b8cd18_idx_and_more')]

    dependencies = [
        ('clist', '0163_update_resource_problems_fields'),
        ('clist', '0167_rename_inherit_medals_to_related_resource_has_inherit_medals_to_related'),
        ('notification', '0041_alter_subscription_account_and_more'),
        ('ranking', '0132_account_rating_prediction'),
        ('ranking', '0135_alter_account_n_subscriptions'),
        ('ranking', '0136_rename_n_subscriptions_account_n_subscribers'),
        ('ranking', '0140_parsestatistics_parse_time'),
        ('tg', '0013_chat_accounts'),
        ('true_coders', '0069_listvalue_true_coders_coder_l_1cff61_idx'),
        ('true_coders', '0070_coder_n_subscribers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='notificatio_contest_559967_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.AddField(
            model_name='subscription',
            name='accounts',
            field=models.ManyToManyField(to='ranking.account'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['contest'], name='notificatio_contest_089a04_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['resource'], name='notificatio_resourc_b72d99_idx'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='coder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='coder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coders',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='true_coders.coder'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='ranking.account'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['enable', 'resource', 'contest'], name='notificatio_enable_2370eb_idx'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_contest_subscriptions', to='clist.contest'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='top_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='with_first_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['resource', 'contest'], name='notificatio_resourc_b8cd18_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['resource', 'contest', 'with_first_accepted'], name='notificatio_resourc_90d51f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['resource', 'contest', 'top_n'], name='notificatio_resourc_b039f3_idx'),
        ),
    ]
