# Generated by Django 5.1.4 on 2024-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0042_edit_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='with_custom_names',
            field=models.BooleanField(default=False),
        ),
    ]
