# Generated by Django 5.1.15 on 2026-03-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0188_alter_contest_options_alter_resource_options'),
        ('notification', '0044_update_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='exclude_contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_subscriptions', to='clist.contest'),
        ),
    ]
