# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 16:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180203_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
