# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 18:22


from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0007_organization_author'),
        ('events', '0005_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', django_enumfield.db.fields.EnumField(default=9, enum=events.models.TeamStatus)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
