# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 01:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0012_coder_phone_number'),
        ('events', '0015_auto_20180206_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_author_set', to='true_coders.Coder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='Participant',
        ),
        migrations.AlterField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(blank=True, to='events.Participant'),
        ),
    ]
