# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 03:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set([('team', 'participant')]),
        ),
    ]
