# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 05:45


from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20180206_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='coder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.Coder'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirt_size',
            field=django_enumfield.db.fields.EnumField(blank=True, default=2, enum=events.models.TshirtSize, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([]),
        ),
    ]
