# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 03:44


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_email_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logins_paths',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
