# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 03:54


from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_logins_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stage', django_enumfield.db.fields.EnumField(default=0, enum=events.models.TeamStatus)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='login',
            unique_together=set([('stage', 'username'), ('team', 'stage')]),
        ),
    ]
