# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 04:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20180216_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
