# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 10:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_login_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='information',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
