# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-20 23:53


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_event_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='standings_urls',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
