# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-21 00:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_standings_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
