# Generated by Django 2.2.10 on 2020-04-03 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20200320_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
