# Generated by Django 2.2.10 on 2020-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(default=3),
        ),
    ]
