# Generated by Django 2.2.10 on 2020-04-16 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_event_addition_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='addition_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
