# Generated by Django 3.1.7 on 2021-03-07 16:44

from django.db import migrations
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_participant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='stage',
            field=django_enumfield.db.fields.EnumField(enum=events.models.TeamStatus),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirt_size',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=events.models.TshirtSize, null=True),
        ),
    ]
