# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20210307_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email_conf',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='fields_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='logins_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='standings_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='participant',
            name='addition_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
