resolver 127.0.0.11 valid=30s ipv6=off;

upstream prod_uwsgi_backend {
  zone prod_uwsgi_backend 64k;
  server prod:8042 resolve;
}

upstream channels-backend {
  zone channels_backend 64k;
  server prod:9042 resolve;
}

upstream devclist {
  zone devclist 64k;
  server dev:10042 resolve max_fails=0 fail_timeout=0;
}

upstream legacy_fastcgi_backend {
  zone legacy_fastcgi_backend 64k;
  server legacy:9000 resolve;
}

upstream pgadmin_backend {
  zone pgadmin_backend 64k;
  server pgadmin:80 resolve;
}

upstream bugsink_backend {
  zone bugsink_backend 64k;
  server bugsink:8000 resolve;
}

upstream healthchecks_backend {
  zone healthchecks_backend 64k;
  server healthchecks:8000 resolve;
}

upstream grafana_upstream {
  zone grafana_upstream 64k;
  server grafana:3000 resolve;
}

upstream netdata_upstream {
  zone netdata_upstream 64k;
  server netdata:19999 resolve;
  keepalive 64;
}
