server {
  listen 443;
  server_name bugsink.clist.by;

  ssl_certificate     /etc/letsencrypt/live/bugsink.clist.by/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/bugsink.clist.by/privkey.pem;

  location = /internal/auth/ {
    internal;

    uwsgi_cache           auth_cache;
    uwsgi_cache_key       "$host:$cookie_sessionid";
    uwsgi_cache_valid     200 60m;
    uwsgi_cache_valid     401 10m;
    uwsgi_cache_use_stale error timeout invalid_header updating http_500 http_503;
    uwsgi_ignore_headers  Vary;

    include               uwsgi_params;
    uwsgi_pass            prod:8042;
    uwsgi_pass_request_body off;
    uwsgi_param           REQUEST_METHOD GET;
    uwsgi_param           CONTENT_LENGTH "";
    uwsgi_param           SCRIPT_NAME "";
    uwsgi_param           PATH_INFO /service_auth/bugsink/;
    uwsgi_param           HTTP_COOKIE $http_cookie;
    uwsgi_param           HTTP_HOST $host;
    uwsgi_param           HTTP_X_FORWARDED_PROTO $scheme;
  }

  location / {
    auth_request /internal/auth/;
    error_page   401 403 = @login;

    proxy_pass http://bugsink:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
  }

  location @login {
    return 302 https://clist.by/login/?next=$scheme://$host$request_uri;
  }
}
