server {
  listen 443;
  server_name healthchecks.clist.by;

  ssl_certificate     /etc/letsencrypt/live/healthchecks.clist.by/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/healthchecks.clist.by/privkey.pem;

  location = /internal/auth/ {
    internal;

    uwsgi_cache           auth_cache;
    uwsgi_cache_key       "$host:$cookie_sessionid";
    uwsgi_cache_valid     200 60m;
    uwsgi_cache_valid     401 10m;
    uwsgi_cache_use_stale error timeout invalid_header updating http_500 http_503;

    include               uwsgi_params;
    uwsgi_pass            prod:8042;
    uwsgi_param           SCRIPT_NAME "";
    uwsgi_param           PATH_INFO /service_auth/healthchecks/;
    uwsgi_param           HTTP_COOKIE $http_cookie;
    uwsgi_param           HTTP_HOST $host;
    uwsgi_param           HTTP_X_FORWARDED_PROTO $scheme;
  }

  location / {
    auth_request     /internal/auth/;
    auth_request_set $hc_email $upstream_http_remote_email;
    error_page       401 403 = @login;

    proxy_pass http://healthchecks:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Remote-User $hc_email;
    proxy_redirect off;
  }

  location @login {
    return 302 https://clist.by/login/?next=$scheme://$host$request_uri;
  }
}
