# Generated by Django 3.1.8 on 2021-05-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0034_auto_20210411_1726'),
        ('chats', '0005_auto_20210523_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='coder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder'),
        ),
    ]
