# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 00:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0004_contest_was_auto_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='was_auto_add',
            field=models.BooleanField(default=False),
        ),
    ]
