# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 00:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0005_auto_20170918_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='was_auto_add',
            new_name='was_auto_added',
        ),
    ]
