# Generated by Django 2.1.7 on 2019-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0006_auto_20170918_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='parse_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='duration_in_secs',
            field=models.IntegerField(blank=True),
        ),
    ]
