# Generated by Django 2.1.7 on 2019-08-18 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0010_auto_20190809_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contest',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
