# Generated by Django 2.1.7 on 2019-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0011_auto_20190818_1125'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time'], name='clist_conte_start_t_9eec7a_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['end_time'], name='clist_conte_end_tim_341782_idx'),
        ),
    ]
