# Generated by Django 2.1.7 on 2019-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0012_auto_20191123_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='calculcate_time',
            field=models.BooleanField(default=False),
        ),
    ]
