# Generated by Django 2.1.7 on 2019-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0013_contest_calculcate_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='calculcate_time',
            new_name='calculate_time',
        ),
    ]
