# Generated by Django 2.1.7 on 2019-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0014_auto_20191201_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='calculate_time',
            field=models.BooleanField(default=True),
        ),
    ]
