# Generated by Django 2.1.7 on 2019-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0015_auto_20191203_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='calculate_time',
            field=models.BooleanField(default=False),
        ),
    ]
