# Generated by Django 2.1.7 on 2019-12-03 11:12

from django.db import migrations
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0021_auto_20191203_1108'),
    ]

    operations = [
        AddDefaultValue(
            model_name='contest',
            name='info',
            value={},
        )
    ]
