# Generated by Django 2.2.10 on 2020-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0027_invisible_default_value'),
    ]

    operations = [
        migrations.RunSQL('''
CREATE OR REPLACE FUNCTION update_timing() RETURNS trigger
    LANGUAGE plpgsql
    AS $$BEGIN
    IF TG_OP='INSERT' THEN
        NEW.created = NOW();
        NEW.modified = NOW();
    ELSIF md5(CAST((OLD.*) AS text)) <> md5(CAST((NEW.*) AS text)) THEN
        NEW.modified = NOW();
    END IF;
    NEW.updated = NOW();
    RETURN NEW;
END
$$;
                          '''),

        migrations.RunSQL('''
DROP TRIGGER IF EXISTS update_timing_contest on clist_contest;
CREATE TRIGGER update_timing_contest
BEFORE INSERT OR UPDATE ON clist_contest FOR EACH ROW EXECUTE PROCEDURE update_timing();
                          '''),
    ]
