# Generated by Django 2.2.10 on 2020-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0030_resource_has_rating_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
