# Generated by Django 2.2.10 on 2020-05-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0034_auto_20200503_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='num_accounts',
            new_name='n_accounts',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='num_contests',
            new_name='n_contests',
        ),
    ]
