# Generated by Django 2.2.10 on 2020-05-28 23:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0037_auto_20200528_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='division',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, null=True, size=None),
        ),
    ]
