# Generated by Django 2.2.10 on 2020-05-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0038_problem_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='division',
            new_name='divisions',
        ),
    ]
