# Generated by Django 2.2.13 on 2020-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0039_auto_20200528_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
