# Generated by Django 2.2.13 on 2020-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0050_delete_problem'),
        ('clist', '0040_contest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='writers_set', to='ranking.Account'),
        ),
    ]
