# Generated by Django 2.2.13 on 2020-06-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0043_problem_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('problems', models.ManyToManyField(blank=True, related_name='tags', to='clist.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
