# Generated by Django 2.2.13 on 2020-07-12 22:16

from django.db import migrations
import django_ltree.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0044_problemtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='title_path',
            field=django_ltree.fields.PathField(blank=True, db_index=True, null=True),
        ),
    ]
