# Generated by Django 2.2.13 on 2020-07-12 22:20

from django.db import migrations
import tqdm

from clist.templatetags.extras import slug


def init_title_path(apps, schema_editor):
    Contest = apps.get_model('clist', 'Contest')
    qs = Contest.objects.all()
    for c in tqdm.tqdm(qs.iterator(), total=qs.count()):
        c.slug = slug(c.title)
        c.title_path = c.slug.strip('-').replace('-', '.')
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0045_contest_title_path'),
    ]

    operations = [
        migrations.RunPython(init_title_path),
    ]
