# Generated by Django 2.2.13 on 2020-07-31 20:13

from django.db import migrations, models
import tqdm


def init_problems_time(apps, schema_editor):
    Problem = apps.get_model('clist', 'Problem')
    qs = Problem.objects.select_related('contest').all()
    for p in tqdm.tqdm(qs.iterator(), total=qs.count()):
        p.time = p.contest.start_time
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0047_resource_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(init_problems_time),
    ]
