# Generated by Django 2.2.13 on 2020-07-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0048_problem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
