# Generated by Django 2.2.13 on 2020-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0049_auto_20200731_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='short_host',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
