# Generated by Django 2.2.13 on 2020-10-10 01:22

from django.db import migrations
import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0050_resource_short_host'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['title'], name='clist_conte_title_a56b78_gist'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['name'], name='clist_probl_name_e9002d_gist'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['host'], name='clist_resou_host_7b7aef_gist'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=pyclist.indexes.GistIndexTrgrmOps(fields=['short_host'], name='clist_resou_short_h_a8f6a1_gist'),
        ),
    ]
