# Generated by Django 2.2.13 on 2020-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0051_auto_20201008_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='n_statistics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timingcontest',
            name='statistic',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
