# Generated by Django 2.2.13 on 2020-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0053_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='n_statistics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
