# Generated by Django 2.2.13 on 2020-11-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0054_n_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='n_statistics',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['updated'], name='clist_conte_updated_2eabaa_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['n_statistics', 'updated'], name='clist_conte_n_stati_77f8cd_idx'),
        ),
    ]
