# Generated by Django 2.2.13 on 2021-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0061_auto_20210301_1947'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contest',
            name='clist_conte_resourc_3c9264_idx',
        ),
        migrations.RemoveIndex(
            model_name='contest',
            name='clist_conte_resourc_4d9b15_idx',
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['resource', 'end_time', 'id'], name='clist_conte_resourc_e74fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['resource', 'start_time', 'id'], name='clist_conte_resourc_05de63_idx'),
        ),
    ]
