# Generated by Django 3.1.7 on 2021-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0066_auto_20210308_2036'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['n_statistics', 'end_time'], name='clist_conte_n_stati_bb8171_idx'),
        ),
    ]
