# Generated by Django 3.1.12 on 2021-08-29 13:16

from datetime import datetime

import tqdm
from django.db import migrations, models


def init_parsed_time(apps, schema_editor):
    Contest = apps.get_model('clist', 'Contest')
    qs = Contest.objects.all()
    for c in tqdm.tqdm(qs.iterator(), total=qs.count()):
        parsed_time = c.info.pop('last_parse_statistics', c.updated)
        if isinstance(parsed_time, str):
            parsed_time = datetime.strptime(parsed_time, '%Y-%m-%d %H:%M:%S.%f+%Z')
        c.parsed_time = parsed_time
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0068_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='parsed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(init_parsed_time),
    ]
