# Generated by Django 3.1.14 on 2022-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0075_contest_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_rated',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
