# Generated by Django 3.1.14 on 2022-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0077_auto_20220320_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
