# Generated by Django 3.1.14 on 2022-05-22 11:14

from django.db import migrations, models


def set_variables(apps, schema_editor):
    Resource = apps.get_model('clist', 'Resource')
    qs = Resource.objects.filter(module__isnull=False).select_related('module')
    for resource in qs:
        resource.multi_account_allowed = resource.module.multi_account_allowed
        resource.has_accounts_infos_update = resource.module.has_accounts_infos_update
        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0083_resource_has_problem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_accounts_infos_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='multi_account_allowed',
            field=models.BooleanField(default=False),
        ),

        migrations.RunPython(set_variables),
    ]
