# Generated by Django 3.1.14 on 2022-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0085_auto_20220522_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
