# Generated by Django 3.1.14 on 2022-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0087_contest_with_medals'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['resource', 'start_time', 'end_time'], name='clist_conte_resourc_7cc518_idx'),
        ),
    ]
