# Generated by Django 3.1.14 on 2022-12-26 14:44

import tqdm
from django.db import migrations


def set_variables(apps, schema_editor):
    Contest = apps.get_model('clist', 'Contest')
    qs = Contest.objects.select_related('timing').filter(timing__isnull=False)
    for c in tqdm.tqdm(qs.iterator(), total=qs.count()):
        c.statistic_timing = c.timing.statistic
        c.notification_timing = c.timing.notification
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0089_auto_20221226_1334'),
    ]

    operations = [
        migrations.RunPython(set_variables),

        migrations.DeleteModel(
            name='TimingContest',
        ),
    ]
