# Generated by Django 3.1.14 on 2022-12-28 17:46

from django.db import migrations, models
from django.db.models import Q


def set_variables(apps, schema_editor):
    Contest = apps.get_model('clist', 'Contest')
    qs = Contest.objects.filter(Q(info__fields__contains=['advanced']) | Q(info__fields__contains=['_advance']))
    qs.update(with_advance=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0091_auto_20221226_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='with_advance',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),

        migrations.RunPython(set_variables),
    ]
