# Generated by Django 3.1.14 on 2023-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0092_contest_with_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_upsolving',
            field=models.BooleanField(default=False),
        ),
    ]
