# Generated by Django 3.1.14 on 2023-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0095_contesttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttag',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
    ]
