# Generated by Django 3.1.14 on 2023-03-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0096_contesttag_is_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttag',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
