# Generated by Django 3.1.14 on 2023-03-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0097_contesttag_aliases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttag',
            name='is_series',
        ),
    ]
