# Generated by Django 3.1.14 on 2023-03-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0099_auto_20230311_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestTag',
            new_name='ContestSeries',
        ),
    ]
