# Generated by Django 3.1.14 on 2023-03-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0100_auto_20230311_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestseries',
            options={'verbose_name_plural': 'Contest series'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clist.contestseries'),
        ),
    ]
