# Generated by Django 3.1.14 on 2023-05-14 17:33

import tqdm
from django.db import migrations, models


def set_times(apps, schema_editor):
    Problem = apps.get_model('clist', 'Problem')
    qs = Problem.objects.all()
    for problem in tqdm.tqdm(qs.iterator(), total=qs.count()):
        contests = list(problem.contests.all())
        if problem.contest:
            contests.append(problem.contest)
        problem.start_time = min([c.start_time for c in contests] + [problem.time])
        problem.end_time = max([c.end_time for c in contests] + [problem.time])
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0101_auto_20230329_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),

        migrations.RunPython(set_times),
    ]
