# Generated by Django 3.1.14 on 2023-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0102_problems_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
