# Generated by Django 3.1.14 on 2023-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0103_remove_null_for_problems_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_account_verification',
            field=models.BooleanField(default=False),
        ),
    ]
