# Generated by Django 3.1.14 on 2023-07-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0054_auto_20230528_1859'),
        ('clist', '0104_resource_has_account_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='editors',
            field=models.ManyToManyField(blank=True, to='true_coders.Coder'),
        ),
    ]
