# Generated by Django 3.1.14 on 2023-07-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0105_editors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_hidden_fields', 'Can view hidden fields'))},
        ),
    ]
