# Generated by Django 3.1.14 on 2023-07-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0106_auto_20230722_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'))},
        ),
    ]
