# Generated by Django 4.2.3 on 2023-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0108_remove_resource_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='standings_kind',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
