# Generated by Django 4.2.3 on 2023-09-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0114_rename_last_rating_update_time_resource_rank_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
