# Generated by Django 4.2.3 on 2023-09-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0115_problem_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='n_rating_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
