# Generated by Django 4.2.3 on 2023-09-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0116_resource_n_rating_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='n_rating_accounts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
