# Generated by Django 4.2.3 on 2023-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0118_problem_archive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='problem_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
