# Generated by Django 4.2.3 on 2023-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0127_resource_has_standings_renamed_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='problems_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
