# Generated by Django 4.2.3 on 2023-11-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0129_contest_n_problems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='n_tries',
            new_name='n_attempts',
        ),
    ]
