# Generated by Django 4.2.3 on 2023-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0130_rename_n_tries_problem_n_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='statistics_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
