# Generated by Django 4.2.3 on 2023-12-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0133_alter_contest_rating_prediction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allow_updating_statistics_for_participants',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
