# Generated by Django 4.2.3 on 2023-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0134_contest_allow_updating_statistics_for_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='auto_remove_started',
            field=models.BooleanField(default=False),
        ),
    ]
