# Generated by Django 4.2.3 on 2023-12-11 02:17

from django.db import migrations, models
from django.db.models import F


def calculate_new_field(apps, schema_editor):
    MyModel = apps.get_model('clist', 'Contest')  # Replace 'myapp' with your app name
    MyModel.objects.update(auto_updated=F('updated'))


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0135_resource_auto_remove_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='auto_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(calculate_new_field),
    ]
