# Generated by Django 4.2.3 on 2023-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0137_alter_contest_auto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='trial_standings_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
