# Generated by Django 4.2.11 on 2024-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0141_problem_skip_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='country_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
