# Generated by Django 4.2.11 on 2024-04-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0142_resource_country_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='country_update_time',
            new_name='country_rank_update_time',
        ),
    ]
