# Generated by Django 4.2.11 on 2024-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0143_rename_country_update_time_resource_country_rank_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='contest_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
