# Generated by Django 4.2.11 on 2024-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0144_resource_contest_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_country_rating',
            field=models.BooleanField(default=False),
        ),
    ]
