# Generated by Django 4.2.11 on 2024-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0147_contest_has_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='has_submissions_tests',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
