# Generated by Django 5.0.6 on 2024-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0151_set_matched_coders_to_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='wait_for_successful_update_timing',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
