# Generated by Django 5.0.6 on 2024-07-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0153_promolink'), ('clist', '0154_promolink_order'), ('clist', '0155_alter_promolink_order'), ('clist', '0156_alter_promolink_desc'), ('clist', '0157_promolink_enable')]

    dependencies = [
        ('clist', '0152_contest_wait_for_successful_update_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='promolinks')),
                ('url', models.URLField()),
                ('order', models.IntegerField(blank=True, default=None)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
