# Generated by Django 5.0.6 on 2024-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0158_resource_has_problem_update'), ('clist', '0159_problem_updated')]

    dependencies = [
        ('clist', '0157_promolink_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_problem_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
