# Generated by Django 5.0.7 on 2024-07-20 21:22

from django.db import migrations, models


def fill_problem_rating_hash(apps, schema_editor):
    Contest = apps.get_model('clist', 'Contest')  # Replace 'myapp' with your app name
    for contest in Contest.objects.filter(info___problems_ratings_hash__isnull=False):
        contest.problem_rating_hash = contest.info.pop('_problems_ratings_hash')
        contest.save(update_fields=['problem_rating_hash', 'info'])


class Migration(migrations.Migration):

    replaces = [('clist', '0159_contest_problem_rating_hash'), ('clist', '0160_contest_problem_rating_update_required_and_more'), ('clist', '0161_auto_20240716_1349'), ('clist', '0162_remove_problem_updated')]

    dependencies = [
        ('clist', '0158_problem_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problem_rating_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.RunPython(fill_problem_rating_hash),
        migrations.AddField(
            model_name='contest',
            name='problem_rating_update_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='statistics_update_required',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE clist_contest ALTER COLUMN problem_rating_update_required SET DEFAULT FALSE',
            reverse_sql='ALTER TABLE clist_contest ALTER COLUMN problem_rating_update_required DROP DEFAULT',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE clist_contest ALTER COLUMN statistics_update_required SET DEFAULT FALSE',
            reverse_sql='ALTER TABLE clist_contest ALTER COLUMN statistics_update_required DROP DEFAULT',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='updated',
        ),
    ]
