# Generated by Django 5.0.7 on 2024-07-28 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0159_update_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None),
        ),
    ]
