# Generated by Django 5.0.7 on 2024-08-11 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0162_resource_has_new_problems'), ('clist', '0163_alter_problem_end_time_alter_problem_start_time_and_more'), ('clist', '0164_problem_from_archive_problem_from_contest'), ('clist', '0165_rename_from_archive_problem_is_archive_and_more'), ('clist', '0166_problem_n_accepted_submissions_and_more'), ('clist', '0167_rename_n_total_submussions_problem_n_total_submissions'), ('clist', '0168_resource_problem_rating_predictor'), ('clist', '0169_alter_problem_kinds_and_more'), ('clist', '0170_alter_problem_divisions_alter_problem_kinds_and_more'), ('clist', '0171_alter_problem_divisions_alter_problem_kinds')]

    dependencies = [
        ('clist', '0161_auto_20240728_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_new_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_archive',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='n_accepted_submissions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='n_total_submissions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='problem_rating_predictor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, db_index=True, default=None, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['resource_id', 'kinds'], name='clist_probl_resourc_b7c8f6_idx'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='divisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_index=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='problem',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, db_index=True, default=[], size=None),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['resource_id', 'divisions'], name='clist_probl_resourc_bc6b00_idx'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='divisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_index=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='problem',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, db_index=True, default=list, size=None),
        ),
    ]
