# Generated by Django 5.1 on 2024-08-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0163_resource_new_problems_update_time'), ('clist', '0164_rename_new_problems_update_time_resource_archive_problems_update_time_and_more'), ('clist', '0165_rename_has_archive_problems_resource_has_problem_archive_and_more')]

    dependencies = [
        ('clist', '0162_resource_edits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='has_new_problems',
            new_name='has_problem_archive',
        ),
        migrations.AddField(
            model_name='resource',
            name='problem_archive_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
