# Generated by Django 5.1 on 2024-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0164_contest_parsed_percentage'), ('clist', '0165_contest_inherit_medals_to_related'), ('clist', '0166_remove_contest_inherit_medals_to_related_and_more'), ('clist', '0167_rename_inherit_medals_to_related_resource_has_inherit_medals_to_related')]

    dependencies = [
        ('clist', '0163_update_resource_problems_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='parsed_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_inherit_medals_to_related',
            field=models.BooleanField(default=False),
        ),
    ]
