# Generated by Django 5.1.3 on 2024-11-23 01:51

import django_add_default_value.add_default_value
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0165_contest_variables_alter_contest_key'), ('clist', '0166_variable_default'), ('clist', '0167_alter_contest_options')]

    dependencies = [
        ('clist', '0164_edit_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(blank=True, max_length=255),
        ),
        django_add_default_value.add_default_value.AddDefaultValue(
            model_name='contest',
            name='variables',
            value={},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'))},
        ),
    ]
