# Generated by Django 5.1.4 on 2024-12-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0166_rename_was_auto_added_contest_is_auto_added'), ('clist', '0167_contest_hide_unsolved_standings_problems'), ('clist', '0168_contest_upload_solved_problems_solutions'), ('clist', '0169_alter_promotion_name')]

    dependencies = [
        ('clist', '0165_contest_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='was_auto_added',
            new_name='is_auto_added',
        ),
        migrations.AddField(
            model_name='contest',
            name='hide_unsolved_standings_problems',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='upload_solved_problems_solutions',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
