# Generated by Django 5.1.4 on 2024-12-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0167_discussion'), ('clist', '0168_discussion_info_discussion_with_problem_discussions_and_more'), ('clist', '0169_alter_problem_index')]

    dependencies = [
        ('clist', '0166_contest_promotion'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('what_id', models.PositiveIntegerField()),
                ('where_id', models.PositiveIntegerField()),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.contest')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.problem')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.resource')),
                ('what_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_what', to='contenttypes.contenttype')),
                ('where_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_where', to='contenttypes.contenttype')),
                ('info', models.JSONField(blank=True, default=dict)),
                ('with_problem_discussions', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('what_type', 'what_id', 'where_type', 'where_id')},
                'indexes': [models.Index(fields=['what_type', 'what_id', 'with_problem_discussions'], name='clist_discu_what_ty_760c53_idx')],
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='index',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
