# Generated by Django 5.1.5 on 2025-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0170_addition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_statistic_medal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
