# Generated by Django 5.1.5 on 2025-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0171_resource_has_statistic_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_account_n_writers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
