# Generated by Django 5.1.5 on 2025-02-23 11:51

from django.db import migrations, models
from django_add_default_value.add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0172_resource_has_account_n_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='finalists_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        AddDefaultValue(
            model_name='contest',
            name='finalists_info',
            value={},
        ),
    ]
