# Generated by Django 5.1.5 on 2025-03-23 22:26

import django_add_default_value.add_default_value
from django.db import migrations, models


def set_has_problem_statistic(apps, schema_editor):
    Resource = apps.get_model('clist', 'Resource')
    for resource in Resource.objects.all():
        contests = resource.contest_set.filter(stage__isnull=True)
        resource.has_problem_statistic = contests.filter(info__fields_types__problems__isnull=False).exists()
        resource.save(update_fields=['has_problem_statistic'])


class Migration(migrations.Migration):

    replaces = [('clist', '0174_resource_has_statistic_place'), ('clist', '0175_resource_has_country_medal'), ('clist', '0176_resource_n_statistics'), ('clist', '0177_contest_elimination_tournament_info'), ('clist', '0178_problem_acceptance_rate_problem_attempt_rate_and_more'), ('clist', '0179_resource_has_problem_statistic')]

    dependencies = [
        ('clist', '0173_contest_finalists_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_statistic_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_country_medal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='n_statistics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='elimination_tournament_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        django_add_default_value.add_default_value.AddDefaultValue(
            model_name='contest',
            name='elimination_tournament_info',
            value={},
        ),
        migrations.AddField(
            model_name='problem',
            name='acceptance_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='attempt_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='partial_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_problem_statistic',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_has_problem_statistic),
    ]
