# Generated by Django 5.1.8 on 2025-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0174_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='allow_delete_archived_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
