# Generated by Django 5.1.8 on 2025-11-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clist', '0176_resource_n_university_accounts'), ('clist', '0177_resource_n_team_accounts'), ('clist', '0178_resource_has_country_place'), ('clist', '0179_contest_link_statistic_timing'), ('clist', '0180_resource_default_account_type')]

    dependencies = [
        ('clist', '0175_resource_allow_delete_archived_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='n_university_accounts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='n_team_accounts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_country_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='link_statistic_timing',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='default_account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'University'), (3, 'Team')], default=1),
        ),
    ]
