# Generated by Django 5.1.14 on 2025-11-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0176_resource_n_university_accounts_squashed_0180_resource_default_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'))},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'))},
        ),
    ]
