# Generated by Django 5.1.14 on 2025-12-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0181_alter_contest_options_alter_resource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icon_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
