# Generated by Django 5.1.14 on 2025-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0182_resource_icon_updated_at_resource_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='resources'),
        ),
    ]
