# Generated by Django 5.1.14 on 2025-12-13 16:23

import pyclist.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0183_resource_icon_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='icon',
        ),
        migrations.AlterField(
            model_name='resource',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, storage=pyclist.storage.OverwriteStorage(), upload_to='resources'),
        ),
    ]
