# Generated by Django 5.1.15 on 2025-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0184_remove_resource_icon_alter_resource_icon_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='failed_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='n_failed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='n_submissions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
