# Generated by Django 5.1.15 on 2025-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0185_problem_failed_rate_problem_n_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submissions_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
