# Generated by Django 5.1.15 on 2026-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0186_problem_submissions_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_submissions_statistics_log',
            field=models.BooleanField(default=False),
        ),
    ]
