# Generated by Django 5.1.15 on 2026-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0187_resource_has_submissions_statistics_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'), ('view_statistics_logs', 'Can view statistics logs'))},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'), ('view_statistics_logs', 'Can view statistics logs'))},
        ),
    ]
