# Generated by Django 5.1.15 on 2026-08-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0188_alter_contest_options_alter_resource_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'), ('view_statistics_logs', 'Can view statistics logs'), ('view_live_updates', 'Can view live updates'))},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('update_statistics', 'Can update statistics'), ('view_private_fields', 'Can view private fields'), ('sort_by_fields', 'Can sort by specific fields'), ('view_statistics_logs', 'Can view statistics logs'), ('view_live_updates', 'Can view live updates'))},
        ),
    ]
