# Generated by Django 6.1 on 2026-08-09 09:46
# ruff: noqa: RUF012

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clist", "0189_alter_contest_options_alter_resource_options"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GistIndexTrgrmOps(fields=["name_en"], name="clist_probl_name_en_996e40_gist"),
        ),
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GistIndexTrgrmOps(fields=["name_ru"], name="clist_probl_name_ru_f2da19_gist"),
        ),
    ]
