# Generated by Django 6.1 on 2026-08-09 11:57
# ruff: noqa: RUF012

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clist", "0190_localized_problem_name_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="problem",
            new_name="clist_problem_name_gist",
            old_name="clist_probl_name_e9002d_gist",
        ),
        migrations.RenameIndex(
            model_name="problem",
            new_name="clist_problem_name_gist-en",
            old_name="clist_probl_name_en_996e40_gist",
        ),
        migrations.RenameIndex(
            model_name="problem",
            new_name="clist_problem_name_gist-ru",
            old_name="clist_probl_name_ru_f2da19_gist",
        ),
    ]
