# Generated by Django 6.1 on 2026-08-14 21:08
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clist", "0191_rename_clist_probl_name_e9002d_gist_clist_problem_name_gist_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="contest",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["title"], name="clist_conte_title_b78cda_gin"),
        ),
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["name"], name="clist_probl_name_244f00_gin"),
        ),
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["name_en"], name="clist_probl_name_244f00_gin-en"),
        ),
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["name_ru"], name="clist_probl_name_244f00_gin-ru"),
        ),
        AddIndexConcurrently(
            model_name="resource",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["host"], name="clist_resou_host_4d57a0_gin"),
        ),
        AddIndexConcurrently(
            model_name="resource",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["short_host"], name="clist_resou_short_h_dde970_gin"),
        ),
    ]
