# Generated by Django 6.1 on 2026-08-14 22:12
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clist", "0192_contest_clist_conte_title_b78cda_gin_and_more"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="contest",
            name="clist_conte_title_a56b78_gist",
        ),
        RemoveIndexConcurrently(
            model_name="problem",
            name="clist_problem_name_gist",
        ),
        RemoveIndexConcurrently(
            model_name="problem",
            name="clist_problem_name_gist-en",
        ),
        RemoveIndexConcurrently(
            model_name="problem",
            name="clist_problem_name_gist-ru",
        ),
        RemoveIndexConcurrently(
            model_name="resource",
            name="clist_resou_host_7b7aef_gist",
        ),
        RemoveIndexConcurrently(
            model_name="resource",
            name="clist_resou_short_h_a8f6a1_gist",
        ),
    ]
