# Generated by Django 6.1 on 2026-08-14 22:58
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("clist", "0193_remove_contest_clist_conte_title_a56b78_gist_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="problem",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["key"], name="clist_probl_key_dcacb4_gin"),
        ),
    ]
