# Generated by Django 6.1 on 2026-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0194_problem_key_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='default_account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'University'), (3, 'Team'), (4, 'Member')], default=1),
        ),
    ]
