# Generated by Django 6.1 on 2026-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0195_alter_resource_default_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='n_member_accounts',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
