# Generated by Django 6.1 on 2026-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # ruff: ignore[mutable-class-default]
        ("clist", "0196_resource_n_member_accounts"),
    ]

    operations = [  # ruff: ignore[mutable-class-default]
        migrations.AddField(
            model_name="resource",
            name="activity_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="activity_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
