# Generated by Django 6.1 on 2026-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0197_resource_activity_score_resource_activity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='medal_win_equals_gold',
            field=models.BooleanField(blank=True, default=None, help_text='Unknown: assume wins equal gold medals until a difference is found, then keep No. Yes: always hide gold medals. No: show wins and gold separately. Choose Unknown again to resume automatic detection.', null=True),
        ),
    ]
