# Generated by Django 3.1.8 on 2021-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chathistroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistroy',
            name='context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
