# Generated by Django 3.1.8 on 2021-05-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20210523_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistroy',
            new_name='ChatHistory',
        ),
    ]
