# Generated by Django 3.1.14 on 2023-04-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chats', '0008_auto_20210703_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('chat_type', models.CharField(choices=[('BLANK', 'Blank'), ('DSCRD', 'Discord'), ('TLGRM', 'Telegram')], db_index=True, default='BLANK', max_length=5)),
                ('chat_id', models.TextField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
