# Generated by Django 5.1.5 on 2025-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='donation_sources')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
