# Generated by Django 5.1.5 on 2025-02-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsource',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
