# Generated by Django 2.1.7 on 2019-08-18 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_auto_20190329_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='history',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
