# Generated by Django 2.2.10 on 2020-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_auto_20190818_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
