# Generated by Django 3.1.7 on 2021-03-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_auto_20210308_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
