# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 00:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='updated',
        ),
        migrations.AlterField(
            model_name='contest',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
