# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 00:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0002_auto_20170918_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
