# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 00:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0003_auto_20170918_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='was_auto_add',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
