# Generated by Django 2.1.7 on 2019-08-08 23:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0007_auto_20190602_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
