# Generated by Django 2.1.7 on 2019-08-09 01:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0008_contest_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
