# Generated by Django 2.1.7 on 2019-08-09 01:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0009_auto_20190809_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
