# Generated by Django 2.1.7 on 2019-12-03 11:08

from django.db import migrations
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0020_auto_20191203_1104'),
    ]

    operations = [
        AddDefaultValue(
            model_name='contest',
            name='calculate_time',
            value=False,
        )
    ]
