# Generated by Django 2.1.7 on 2019-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0022_auto_20191203_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
