# Generated by Django 2.1.7 on 2020-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0023_auto_20191209_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='profile_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
