# Generated by Django 2.1.7 on 2020-02-03 01:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0024_resource_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
