# Generated by Django 2.2.10 on 2020-02-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0025_resource_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='profile_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
