# Generated by Django 2.2.10 on 2020-02-17 14:42

from django.db import migrations
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0026_auto_20200214_0028'),
    ]

    operations = [
        AddDefaultValue(
            model_name='contest',
            name='invisible',
            value=False,
        )
    ]
