# Generated by Django 2.2.10 on 2020-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0031_banner_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
