# Generated by Django 2.2.10 on 2020-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0033_remove_banner_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='num_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='num_contests',
            field=models.IntegerField(default=0),
        ),
    ]
