# Generated by Django 2.2.13 on 2020-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0042_auto_20200616_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
