# Generated by Django 2.2.13 on 2020-12-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0055_auto_20201128_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='n_partial',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='n_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
