# Generated by Django 2.2.13 on 2021-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0056_auto_20201205_1232'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['invisible'], name='clist_conte_invisib_5380ed_idx'),
        ),
    ]
