# Generated by Django 2.2.13 on 2021-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0057_auto_20210227_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='invisible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
