# Generated by Django 2.2.13 on 2021-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0058_auto_20210227_1931'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contest',
            name='clist_conte_invisib_5380ed_idx',
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['-invisible'], name='clist_conte_invisib_852bbb_idx'),
        ),
    ]
