# Generated by Django 2.2.13 on 2021-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0060_auto_20210227_1943'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['resource', 'end_time'], name='clist_conte_resourc_3c9264_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['resource', 'start_time'], name='clist_conte_resourc_4d9b15_idx'),
        ),
    ]
