# Generated by Django 2.2.13 on 2021-03-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0062_auto_20210301_2008'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['title'], name='clist_conte_title_99b76a_idx'),
        ),
    ]
