# Generated by Django 3.1.7 on 2021-03-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0064_auto_20210308_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.resource'),
        ),
    ]
