# Generated by Django 3.1.12 on 2021-09-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0069_contest_parsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='accounts_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
