# Generated by Django 3.1.13 on 2021-10-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0071_contest_has_hidden_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='has_hidden_results',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
