# Generated by Django 3.1.14 on 2022-01-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0072_auto_20211030_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clist.contest'),
        ),
    ]
