# Generated by Django 3.1.14 on 2022-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0074_auto_20220109_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='kind',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
