# Generated by Django 3.1.14 on 2022-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0076_resource_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_rated',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
