# Generated by Django 3.1.14 on 2022-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0078_resource_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['resource_id', 'rating'], name='clist_probl_resourc_ab780d_idx'),
        ),
    ]
