# Generated by Django 3.1.14 on 2022-04-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0079_auto_20220417_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contests',
            field=models.ManyToManyField(blank=True, related_name='problem_set', to='clist.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clist.contest'),
        ),
    ]
