# Generated by Django 3.1.14 on 2022-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0082_problem_n_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_problem_rating',
            field=models.BooleanField(default=False),
        ),
    ]
