# Generated by Django 3.1.14 on 2022-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0084_auto_20220522_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='multi_account_allowed',
            new_name='has_multi_account',
        ),
    ]
