# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 01:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0001_initial'),
        ('ranking', '0003_auto_20170924_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='coder',
        ),
        migrations.AddField(
            model_name='account',
            name='coders',
            field=models.ManyToManyField(blank=True, to='true_coders.Coder'),
        ),
    ]
