# Generated by Django 2.1.7 on 2019-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20190606_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(max_length=1024),
        ),
    ]
