# Generated by Django 2.1.7 on 2019-08-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20190811_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='solving',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='upsolving',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
