# Generated by Django 2.1.7 on 2019-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_auto_20190818_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
