# Generated by Django 2.1.7 on 2019-11-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0013_statistics_place_as_int'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['place_as_int', '-solving'], name='ranking_sta_place_a_c7984a_idx'),
        ),
    ]
