# Generated by Django 2.1.7 on 2020-01-07 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0018_module_has_accounts_infos_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
