# Generated by Django 2.1.7 on 2020-01-27 22:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0024_resource_profile_url'),
        ('ranking', '0019_auto_20200107_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('filter_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('score_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
