# Generated by Django 2.1.7 on 2020-01-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0020_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
