# Generated by Django 2.2.10 on 2020-02-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0024_autorating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorating',
            old_name='filters',
            new_name='info',
        ),
    ]
