# Generated by Django 2.2.10 on 2020-02-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0025_auto_20200119_1008'),
        ('clist', '0026_auto_20200214_0028'),
        ('ranking', '0025_auto_20200214_0035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('contest', 'party')},
        ),
    ]
