# Generated by Django 2.2.10 on 2020-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0031_remove_statistics_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
