# Generated by Django 2.2.10 on 2020-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0032_account_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
