# Generated by Django 2.2.10 on 2020-05-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0036_account_n_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
