# Generated by Django 2.2.10 on 2020-05-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0044_auto_20200511_1312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'last_activity', 'country'], name='ranking_acc_resourc_ab54a5_idx'),
        ),
    ]
