# Generated by Django 2.2.10 on 2020-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0046_account_rating50'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'rating50'], name='ranking_acc_resourc_a84e72_idx'),
        ),
    ]
