# Generated by Django 2.2.10 on 2020-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0047_auto_20200511_1810'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['contest', 'place_as_int', '-solving', 'id'], name='ranking_sta_contest_4a289d_idx'),
        ),
    ]
