# Generated by Django 2.2.10 on 2020-05-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0049_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
