# Generated by Django 2.2.13 on 2020-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0050_delete_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='n_writers',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
