# Generated by Django 2.2.13 on 2020-10-03 21:56

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0052_account_duplicate'),
    ]

    operations = [
        TrigramExtension(),
    ]
