# Generated by Django 2.2.13 on 2021-03-01 01:04

import django.db.models.functions.text
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0056_auto_20201128_2316'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=pyclist.indexes.ExpressionIndex(expressions=[django.db.models.functions.text.Upper('key')], name='ranking_account_aa0071_idx'),
        ),
    ]
