# Generated by Django 2.2.13 on 2021-03-01 01:04

from django.db import migrations
import django.db.models.functions.text
import django_expression_index.index


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0056_auto_20201128_2316'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=django_expression_index.index.ExpressionIndex(expressions=[django.db.models.functions.text.Upper('key')], name='ranking_account_aa0071_idx'),
        ),
    ]
