# Generated by Django 3.1.7 on 2021-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0057_auto_20210301_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='autorating',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stage',
            name='filter_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stage',
            name='score_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='addition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
