# Generated by Django 3.1.12 on 2021-08-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0059_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_contests', 'rating'], name='ranking_acc_resourc_fbe971_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_contests', 'rating50'], name='ranking_acc_resourc_297811_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['resource', 'n_contests', 'country'], name='ranking_acc_resourc_49006c_idx'),
        ),
    ]
