# Generated by Django 3.1.14 on 2022-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0064_auto_20220320_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='new_global_rating',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
