# Generated by Django 3.1.14 on 2022-03-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0065_auto_20220321_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='global_rating',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
