# Generated by Django 3.1.14 on 2023-02-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('true_coders', '0051_coder_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('activity_type', models.CharField(choices=[('fav', 'Favorite'), ('lik', 'Like'), ('sol', 'Solved'), ('rej', 'Reject')], max_length=3)),
                ('object_id', models.PositiveIntegerField()),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['coder', 'activity_type', 'content_type', 'object_id'], name='favorites_a_coder_i_bb7024_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['content_type', 'object_id', 'activity_type'], name='favorites_a_content_b9f745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('coder', 'activity_type', 'content_type', 'object_id')},
        ),
    ]
