# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 16:45


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0006_auto_20180204_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_author_set', to='true_coders.Coder'),
        ),
    ]
