# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 18:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0007_organization_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
