# Generated by Django 2.1.7 on 2019-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0015_auto_20180520_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32),
        ),
    ]
