# Generated by Django 2.1.7 on 2019-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0016_auto_20190329_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
