# Generated by Django 2.1.7 on 2019-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0022_coder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
