# Generated by Django 2.1.7 on 2020-01-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0023_auto_20191209_0955'),
        ('true_coders', '0024_filter_contests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='contests',
        ),
        migrations.AddField(
            model_name='filter',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clist.Contest'),
        ),
    ]
