# Generated by Django 3.1.8 on 2021-04-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0032_auto_20210308_1449'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['contest'], name='true_coders_contest_b952b4_idx'),
        ),
    ]
