# Generated by Django 3.1.8 on 2021-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0033_auto_20210411_1719'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['coder'], name='true_coders_coder_i_5f840b_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['coder', 'contest'], name='true_coders_coder_i_56edcb_idx'),
        ),
    ]
