# Generated by Django 3.1.8 on 2021-05-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0034_auto_20210411_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='n_contests',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
