# Generated by Django 3.1.12 on 2021-07-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0036_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='coder',
            new_name='owner',
        ),
    ]
