# Generated by Django 3.1.13 on 2021-10-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0044_auto_20210703_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='tshirt_size',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
