# Generated by Django 3.1.14 on 2022-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0048_auto_20220111_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='global_rating',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
