# Generated by Django 3.1.14 on 2023-05-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0103_remove_null_for_problems_times'),
        ('true_coders', '0051_coder_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('verdict', models.CharField(choices=[('AC', 'Solved'), ('WA', 'Reject'), ('HT', 'Hidden'), ('PS', 'Partial')], max_length=2)),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='true_coders.coder')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
