# Generated by Django 3.1.14 on 2023-05-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0103_remove_null_for_problems_times'),
        ('true_coders', '0053_auto_20230520_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderproblem',
            name='coder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='true_coders.coder'),
        ),
        migrations.AlterField(
            model_name='coderproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='clist.problem'),
        ),
    ]
