# Generated by Django 4.2.3 on 2023-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0054_auto_20230528_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='start_time_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='start_time_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
