# Generated by Django 4.2.3 on 2023-08-21 00:31

import django.contrib.postgres.fields
from django.db import migrations, models
import true_coders.models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0057_filter_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=true_coders.models._get_default_week_days, size=None),
        ),
    ]
