# Generated by Django 4.2.3 on 2023-08-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0058_filter_week_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
