# Generated by Django 4.2.3 on 2023-09-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0113_resource_last_rating_update_time'),
        ('true_coders', '0059_filter_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('coder_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='true_coders.coderlist')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clist.problem')),
            ],
            options={
                'unique_together': {('coder_list', 'problem')},
            },
        ),
    ]
