# Generated by Django 4.2.3 on 2023-09-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clist', '0113_resource_last_rating_update_time'),
        ('true_coders', '0060_listproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='clist.problem'),
        ),
    ]
