# Generated by Django 4.2.3 on 2023-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0061_alter_listproblem_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderlist',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='coderlist',
            name='shared_with_coders',
            field=models.ManyToManyField(blank=True, related_name='shared_list_set', to='true_coders.coder'),
        ),
    ]
