# Generated by Django 4.2.3 on 2023-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0062_coderlist_access_level_coderlist_shared_with_coders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderlist',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('selective', 'Selective')], default='private', max_length=10),
        ),
    ]
