# Generated by Django 4.2.3 on 2023-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0065_alter_coderlist_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='auto_detect_country',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
