# Generated by Django 4.2.3 on 2023-11-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('true_coders', '0066_coder_auto_detect_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_starts', to='true_coders.coder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['coder', 'content_type', 'object_id'], name='true_coders_coder_i_49ef2a_idx')],
                'unique_together': {('coder', 'content_type', 'object_id')},
            },
        ),
    ]
