# Generated by Django 4.2.3 on 2023-12-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0067_virtualstart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualStart',
        ),
    ]
