# Generated by Django 5.1.5 on 2025-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('true_coders', '0073_coder_n_listvalues'), ('true_coders', '0074_rename_with_names_coderlist_custom_names'), ('true_coders', '0075_coderlist_account_update_delay'), ('true_coders', '0076_coderlist_locale'), ('true_coders', '0077_alter_coderlist_locale')]

    dependencies = [
        ('true_coders', '0072_add_coderlist_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='n_listvalues',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.RenameField(
            model_name='coderlist',
            old_name='with_names',
            new_name='custom_names',
        ),
        migrations.AddField(
            model_name='coderlist',
            name='account_update_delay',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderlist',
            name='locale',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian')], max_length=5, null=True),
        ),
    ]
