# Generated by Django 5.1.15 on 2026-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_coders', '0073_update_coderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='bookmarks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
