# Generated by Django 6.1 on 2026-08-14 21:08
# ruff: file-ignore[mutable-class-default]

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations

import pyclist.indexes


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("true_coders", "0074_coder_bookmarks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="coder",
            index=pyclist.indexes.GinIndexTrgrmOps(fields=["username"], name="true_coders_usernam_51439c_gin"),
        ),
    ]
