# Generated by Django 6.1 on 2026-08-14 22:12
# ruff: file-ignore[mutable-class-default]

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("true_coders", "0075_coder_true_coders_usernam_51439c_gin"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="coder",
            name="true_coders_usernam_c4656d_gist",
        ),
    ]
